### PR TITLE
src/debug.c: detect more scene trees

### PR DESCRIPTION
**Pull request by Consolatis**
and resolve workspaces names + truncate everything.
Also added app_id / WM_CLASS to `view`.

It now looks like
```
                                            X     Y        Node
                                         ----  ----  ----------------
 server->scene                              0     0  [0xaaaaaba930d0]
   +-- output->layer-background          1280     0  [0xaaaaabbc15a0]
   +-- output->layer-bottom              1280     0  [0xaaaaabbc16c0]
   +-- output->layer-background             0     0  [0xaaaaabbb7f60]
   +-- output->layer-bottom                 0     0  [0xaaaaabbb9510]
   +-- server->always_on_bottom             0     0  [0xaaaaaba931b0]
   +-- server->view_tree                    0     0  [0xaaaaaba93240]
      +-- Workspace 1                       0     0  [0xaaaaaba93510]
         +-- seat->region_overlay           0     0  [0xaaaaabd59720]
            +-- rect                        0     0  [0xaaaaabd553e0]
         +-- view (foot)                  304   130  [0xaaaaabd01890]
            +-- view->ssd                 304   130  [0xaaaaabd01f80]
                   <skipping children>
            +-- view->scene_node          304   130  [0xaaaaabd019c0]
               +-- tree                   304   130  [0xaaaaabd01b60]
                  +-- surface             304   130  [0xaaaaabd01ce0]
                  +-- tree                304   130  [0xaaaaabd4cb90]
                     +-- surface          304   130  [0xaaaaabd4cd10]
            +-- view->resize_indicator    623   366  [0xaaaaabcb0190]
               +-- rect                   623   366  [0xaaaaabd53d60]
               +-- rect                   624   367  [0xaaaaabd53df0]
               +-- buffer                 628   371  [0xaaaaabd54270]
      +-- Workspace 2                       0     0  [0xaaaaaba935a0]
      +-- Workspace 3                       0     0  [0xaaaaaba93630]
      +-- Workspace 4                       0     0  [0xaaaaaba936c0]
      +-- Workspace 5                       0     0  [0xaaaaaba93780]
   +-- server->always_on_top                0     0  [0xaaaaaba932d0]
   +-- server->xdg_popup_tree               0     0  [0xaaaaaba93360]
   +-- server->unmanaged_tree               0     0  [0xaaaaaba933f0]
   +-- server->menu_tree                    0     0  [0xaaaaaba93480]
          <skipping children>
   +-- seat->drag.icons                     0     0  [0xaaaaaba4c430]
   +-- output->osd_tree                     0     0  [0xaaaaabbb9ce0]
   +-- output->layer-top                    0     0  [0xaaaaabbb96b0]
   +-- output->layer-overlay                0     0  [0xaaaaabbb9850]
   +-- output->layer_popup_tree             0     0  [0xaaaaabbb99f0]
   +-- output->session_lock_tree            0     0  [0xaaaaabbb9e00]
   +-- output->osd_tree                     0     0  [0xaaaaabbc06b0]
   +-- output->layer-top                 1280     0  [0xaaaaabbc0230]
   +-- output->layer-overlay             1280     0  [0xaaaaabbc0350]
   +-- output->layer_popup_tree             0     0  [0xaaaaabbc0470]
   +-- output->session_lock_tree            0     0  [0xaaaaabbc07d0]
```

### CODE REVIEW

**Comment by tokyo4j** [comment]
I suggest adding `server->seat.region_overlay.tree`.
```diff
diff --git a/src/debug.c b/src/debug.c
index be43b4fc..81ec7318 100644
--- a/src/debug.c
+++ b/src/debug.c
@@ -122,6 +122,9 @@ get_special(struct server *server, struct wlr_scene_node *node)
 	if (node == &server->seat.drag.icons->node) {
 		return "server->seat.drag.icons";
 	}
+	if (node == &server->seat.region_overlay.tree->node) {
+		return "server->seat.region_overlay.tree";
+	}
 #if HAVE_XWAYLAND
 	if (node == &server->unmanaged_tree->node) {
 		return "server->unmanaged_tree";
```

**Comment by Consolatis** [comment]
Thanks, will add.

Also potentially missing:
- osd window outlines
- resize indicator

**Comment by Consolatis** [comment]
Everything should now be shown correctly, updated the current state in the post on top.

**Comment by johanmalm** [comment]
Really nice. Thanks.

**Pull request merged**
