### PR TITLE
nls: add native language support

### PR DESCRIPTION
**Pull request by 01micko**
- adds labwc.pot and po files for de, es, it and sv
- added notes in NEWS.md and CONTRIBUTING.md
- addresses #269
- conditional upon `msgfmt` being installed
- can be disabled at build time

### CODE REVIEW

**Comment by Consolatis** [comment]
The diff looks good to me but I didn't actually test the PR yet.

**Comment by 01micko** [comment]
Oh no! A typo in CONTRIBUTING.md

`s/there/their/`

Fix a little later, stuff to do right now.

**Comment by johanmalm** [comment]
Great effort.

**Comment by 01micko** [comment]
Thanks @johanmalm :smile:

**Comment by 01micko** [comment]
You too @Consolatis :smile:

**Pull request merged**
