### PR TITLE
xdg-shell: set view position before view_maximize()

### PR DESCRIPTION
**Pull request by johanmalm**
...on first map so that view->unmaximized_geometry is known even if an
xdg-shell application started in maximized mode.

Fixes issue #305
Reported-by: @01micko

### CODE REVIEW

**Comment by johanmalm** [comment]
@01micko @Consolatis any chance of checking this one?

**Comment by Consolatis** [comment]
When I start `foot -m` and then un-maximize it, it is still way smaller than when starting foot without `-m`. This might be related to foot as well though.

Left: started normally. Right: started via `-m` and then un-maximized.
foobar

**Comment by 01micko** [comment]
With each application, the bug seemed to be reproduced **_but_** I then resized the minimised app to something reasonable and at least for vivaldi-snapshot and firefox the bug is gone after a few tests however foot shows the same problem as @Consolatis ' screencap above. Maybe @dnkl  can shed some light.

**Comment by dnkl** [comment]
Took a quick look, and from what I can see, foot never receives a configure event with width=0 and height=0 (which indicates that foot should choose its own size).

**Comment by dnkl** [comment]
In other words, I don't see foot doing anything wrong here - it just respond to, and respects, the size hints sent from labwc

**Comment by 01micko** [comment]
@dnkl makes sense in the context of those 2 constants. Thanks.

**Comment by johanmalm** [comment]
I've pushed another commit to set a fallback geometry if `view->unmaximized_geometry` is empty on first unmaximize.
This with works fine with GTK/Qt apps as well as `foot -m`.

I've tried adding a configure with width=0 and height=0, but can't seem to get sensible results (tried mostly with `foot -m` and `qterminal -platform wayland`. I'm sure it's doable, but I can't work it out.

**Pull request merged**
