### PR TITLE
Use "bemenu-run -n" for the A-F3 default keybind to be on top of panels

### PR DESCRIPTION
**Pull request by Consolatis**
Fixes
- #474

I can't test this as I don't even have bemenu installed but the [man page](https://github.com/Cloudef/bemenu/blob/master/man/bemenu.1.scd.in#L103) for `-n` made sense.

### CODE REVIEW

**Comment by datMaffin** [comment]
I tried to compile and run your branch ([Consolatis:issue/474_bemenu](https://github.com/Consolatis/labwc/tree/issue/474_bemenu)), but I ran into linking errors: 
```
/nix/store/rq6bh3qfrqnyqwik0w3q6w180zg3w2pa-binutils-2.38/bin/ld: labwc.p/src_seat.c.o: in function `new_pointer':
/home/user/Documents/labwc-consolatis/build/../src/seat.c:157: undefined reference to `wlr_pointer_from_input_device'
/nix/store/rq6bh3qfrqnyqwik0w3q6w180zg3w2pa-binutils-2.38/bin/ld: labwc.p/src_seat.c.o: in function `new_keyboard':
/home/user/Documents/labwc-consolatis/build/../src/seat.c:171: undefined reference to `wlr_keyboard_from_input_device'
/nix/store/rq6bh3qfrqnyqwik0w3q6w180zg3w2pa-binutils-2.38/bin/ld: labwc.p/src_seat.c.o: in function `new_touch':
/home/user/Documents/labwc-consolatis/build/../src/seat.c:189: undefined reference to `wlr_touch_from_input_device'
```

I do not really understand why, though. The branch labwc/labwc did compile successfully previously.
I would guess that wlroots-0.16.0-dev changed something like the naming of the now missing functions(?).

Anyway pretty sure that the commit looks good.

**Comment by Consolatis** [comment]
That sounds like your wlroots-dev version is too old. So if updating that one doesn't work you could use something like this:
```shell
meson configure --force-fallback-for=wlroots build
meson subprojects update wlroots
meson compile -C build
```

**Comment by datMaffin** [comment]
Can confirm that this change works as expected for me.

**Comment by Consolatis** [comment]
Not changing the defaults: https://github.com/labwc/labwc/issues/474#issuecomment-1212128204

**Pull request closed without merging**
