### PR TITLE
ssd: use `view->pending` for size calculations to avoid the titlebar being out-of-sync with the view size

### PR DESCRIPTION
**Pull request by johanmalm**
@tsujan - testing welcome (I can't reproduce the bug, so can't verify that this fixes it)

### CODE REVIEW

**Comment by tsujan** [comment]
Unfortunately the issue happened again after applying the patch and restarting LabWC (exiting and logging in) — or one may say "fortunately", because there's no need to wait. It happened when I snapped to the bottom quickly for the 7th or 8th time:

qterminal

Can it be related to QtWayland, or even wlroots itself?

**Comment by Consolatis** [comment]
I think using `view->current` in ssd calculations is correct:

In the #1194 case what should happen is a callchain like this
- `interactive_finish()`
  - `view_snap_to_edge()` 
    - `view_apply_tiled_geometry()`
      - `view_move_resize()`
        - `view->impl->configure()`
        - Once we get the commit from the surface via `handle_commit()`:
          - `view_impl_apply_geometry()` (which updates `current->width` and `current->height`)
            - `view_moved()`
              - `ssd_update_geometry()`

That should mean that the SSD should only use the `->current` values for its calculations to have it synced with what was commited / acknowledged from the client.

@tsujan are we talking about a wayland native application or a xwayland one? `A-Tab` should show it either as `[xdg-shell]` or `[xwayland]`.

**Comment by tsujan** [comment]
> are we talking about a wayland native application or a xwayland one?

Two native Wayland apps (xdg-shell).

**Comment by Consolatis** [comment]
This may happen when the clients doesn't respond fast enough, do you have anything like
`client (some_client_app_id) did not respond to configure request in 100 ms` in your logs?

**Comment by tsujan** [comment]
The system log is clean. `~/.local/share/sddm/wayland-session.log` only shows lines like this about LabWC:

```
00:25:27.484 [ERROR] [../labwc-0.6.5/src/desktop.c:422] Unknown node detected
```

**Comment by Consolatis** [comment]
Sorry, deleted my earlier question here and moved it to the issue itself. I thought I was fast enough before you saw it, seems that was not the case :)

**Comment by johanmalm** [comment]
> I think using `view->current` in ssd calculations is correct:
> 
> In the #1194 case what should happen is a callchain like this
> 
>     * `interactive_finish()`
>       
>       * `view_snap_to_edge()`
>         
>         * `view_apply_tiled_geometry()`
>           
>           * `view_move_resize()`
>             
>             * `view->impl->configure()`
> 
>     * Once we get the commit from the surface via `handle_commit()`:
>       
>       * `view_impl_apply_geometry()` (which updates `current->width` and `current->height`)
>         
>         * `view_moved()`
>           
>           * `ssd_update_geometry()`
> 
> 
> That should mean that the SSD should only use the `->current` values for its calculations to have it synced with what was commited / acknowledged from the client.
> 
> @tsujan are we talking about a wayland native application or a xwayland one? `A-Tab` should show it either as `[xdg-shell]` or `[xwayland]`.

Thanks for analyzing @Consolatis 
I just went on a trial-n-error hunch. Will delete that branch :blush:

**Pull request closed without merging**
