### PR TITLE
Add common/strdup-printf.c

### PR DESCRIPTION
**Pull request by johanmalm**

### CODE REVIEW

**Comment by johanmalm** [comment]
@Sachin-Bhat for info.

**Comment by Sachin-Bhat** [comment]
Noted.

**Comment by johanmalm** [comment]
Ready from my perspective.

**Comment by Consolatis** [comment]
PR itself looks good to me.

Unrelated to this PR I stumbled on this part that seems a bit strange:

https://github.com/labwc/labwc/pull/959/files#diff-77c463bc6f74f9247b2dea0b5e282b23706a577c5127c69fe0507ef112168135R129-R142

We are returning a `const char *`  with heap allocated memory. And then casting it to a void pointer to free it.
Shouldn't we return a `char *` for `build_path()` instead?

**Comment by johanmalm** [comment]
Thanks for review.
Good pick up ref the `const char`. I've taken the liberty of adding a commit to un-constify.

**Pull request merged**
