### PR TITLE
protocols: remove redundant wlr-output-management

### PR DESCRIPTION
**Pull request by johanmalm**

### CODE REVIEW

**Comment by Consolatis** [comment]
Nice catch. Seems it was not even compiled in `protocols/meson.build` either

**Comment by johanmalm** [comment]
> Nice catch. Seems it was not even compiled in `protocols/meson.build` either

Yes, that's how I spotted it. I don't think it's ever been needed :smile:

**Comment by Sunderland93** [comment]
This protocol is needed for tools like kanshi or wdisplays. This utilities will not work anymore?

**Comment by johanmalm** [comment]
Yes. As Consolatis said. No functionality has changed. I use kanshi every day and it still works fine.
Sorry for poorly worded PR title - should have made it clearer.

**Pull request merged**
