### PR TITLE
Implement XWayland size hints

### PR DESCRIPTION
**Pull request by misyltoad**
Also has a fix for janky resizing when reaching a single min extent

### CODE REVIEW

**Comment by Joshua-Ashton** [comment]
Sec, there is an error in this PR.

**Comment by Joshua-Ashton** [comment]
Fixed.

**Comment by johanmalm** [comment]
Just a thought. Might it be better to implement this directly in the xwayland.c file in the move() and configure() functions.
That way it'll apply to other attempts to configure/move too - for example SnapToEdge :smile:

**Comment by Joshua-Ashton** [comment]
Possibly ye, will look into it.

**Comment by Joshua-Ashton** [comment]
Should handle it there now and also avoided a judder in cursor if you snapped to min extent too quickly

**Pull request merged**
