### PR TITLE
view: ensure output is usable before setting adaptive sync

### PR DESCRIPTION
**Pull request by Consolatis**
Fixes
- #2337

### CODE REVIEW

**Comment by Consolatis** [comment]
Also needs to be backported to v0.7 which doesn't check `view->output` either.

**Comment by johanmalm** [comment]
LGTM. @kode54 I'd be good to get your verification if you've got time.

**Comment by kode54** [comment]
@johanmalm Verified working. Thanks again!

**Comment by jlindgren90** [comment]
This causes an `assert` fail and crash for me, when enabling an output that was previously disabled.
Partial backtrace (line numbers are off, it's my `dev` branch):

```
#4  0x00007087fd644177 in __assert_fail () at /usr/lib/libc.so.6
#5  0x00006525829f83a8 in output_enable_adaptive_sync (output=<optimized out>, enabled=<optimized out>)
    at ../src/output.c:1092
#6  0x00006525829f9582 in output_config_apply (server=0x7ffcce1d9740, config=0x652588361ca0) at ../src/output.c:586
#7  handle_output_manager_apply (listener=0x7ffcce1d9ee0, data=0x652588361ca0) at ../src/output.c:728
#8  0x00007087fe67747e in wl_signal_emit_mutable () at /usr/lib/libwayland-server.so.0
```

It looks like when the output is in the process of being enabled, but the new state has not been committed yet, `wlr_output->enabled` is still `false`. So it's not safe to `assert` that it's `true` in `output_enable_adaptive_sync`.

**Comment by Consolatis** [comment]
Somehow missed  the pre-initial commit code path. The backport in #2347 is not using the assert() so that one should be safe.
Thanks for fixing

**Pull request merged**
