### PR TITLE
menu: Reuse action argument parsing from rcxml.c

### PR DESCRIPTION
**Pull request by Consolatis**
This fixes being unable to use the `direction` argument in menu entries.

Reported-by: mahk via IRC

### CODE REVIEW

**Comment by johanmalm** [comment]
Very nice indeed. Great to combined the action-filling code of menu.c and rcxml.c

How would you feel about moving `rcxml_fill_action()` to `action.c` and calling it something like `action_parse_one_entry()` or similar. That way we remove the coupling between `menu.c' and `rcxml.h`

**Comment by Consolatis** [comment]
`action_parse_xml_arg()`?

**Comment by johanmalm** [comment]
> > and calling it something like `action_parse_one_entry()` or similar.
> 
> What about `action_parse_xml_arg()` or `action_parse_config_arg()`?

I like the first one better. How about `action_parse_xml_node()` considering we pass a nodename to it.

**Comment by Consolatis** [comment]
- Changed to `action_arg_from_xml_node()` but can change if you prefer.
- Moved the function to `src/action.c` and updated the commit message.

**Pull request merged**
