### PR TITLE
theme: add option osd.window-switcher.padding

### PR DESCRIPTION
**Pull request by johanmalm**
Fixes: issue #969

### CODE REVIEW

**Comment by Consolatis** [comment]
Still not quite the same, old vs new:
20230629_22h51m08s_grim
20230629_22h51m57s_grim

I think the main issue is that we are now using `osd.border.width` for the outer border of the OSD and the selection box itself which was hardcoded before to 6 pixels. Introduced by 11ff820105ed04e8921f165efde638c1d8967e18

**Comment by Consolatis** [comment]
Alright, some progress: old vs adjusted
20230630_19h56m35s_grim
20230630_20h14m12s_grim

Settings used:
- `osd.window-switcher.item.padding.y: 2`
- `osd.window-switcher.padding: 4`
- line width of the selection box: `osd.window-switcher.border * 2` (this one should be its own var)

**Comment by Consolatis** [comment]
Got a bit tighter with the following code changes:
20230701_02h04m12s_grim

<details><summary>osd.diff</summary>

```diff
diff --git a/docs/themerc b/docs/themerc
index 03bb3216..dc699a7b 100644
--- a/docs/themerc
+++ b/docs/themerc
@@ -54,6 +54,7 @@ osd.border.width: 1
 osd.label.text.color: #000000
 
 osd.window-switcher.width: 600
-osd.window-switcher.padding: 1
+osd.window-switcher.padding: 4
 osd.window-switcher.item.padding.x: 10
-osd.window-switcher.item.padding.y: 6
+osd.window-switcher.item.padding.y: 1
+osd.window-switcher.selection.border.width: 2
diff --git a/include/theme.h b/include/theme.h
index df6fbab2..e0f2aae4 100644
--- a/include/theme.h
+++ b/include/theme.h
@@ -71,6 +71,7 @@ struct theme {
 	int osd_window_switcher_padding;
 	int osd_window_switcher_item_padding_x;
 	int osd_window_switcher_item_padding_y;
+	int osd_window_switcher_selection_border_width;
 
 	/* textures */
 	struct lab_data_buffer *xbm_close_active_unpressed;
diff --git a/src/osd.c b/src/osd.c
index f95d8031..40339cee 100644
--- a/src/osd.c
+++ b/src/osd.c
@@ -412,14 +412,15 @@ render_osd(struct server *server, cairo_t *cairo, int w, int h,
 			/* Highlight current window */
 			struct wlr_fbox fbox = {
 				.x = theme->osd_border_width + theme->osd_window_switcher_padding,
-				.y = y - theme->osd_border_width,
+				.y = y - theme->osd_window_switcher_selection_border_width,
 				.width = theme->osd_window_switcher_width
 					- 2 * theme->osd_border_width
 					- 2 * theme->osd_window_switcher_padding,
 				.height = theme->osd_window_switcher_item_height
-					+ 2 * theme->osd_border_width,
+					+ theme->osd_window_switcher_selection_border_width,
 			};
-			draw_cairo_border(cairo, fbox, theme->osd_border_width);
+			draw_cairo_border(cairo, fbox,
+				theme->osd_window_switcher_selection_border_width);
 			cairo_stroke(cairo);
 		}
 
diff --git a/src/theme.c b/src/theme.c
index 03d54a9e..c687cc3e 100644
--- a/src/theme.c
+++ b/src/theme.c
@@ -141,9 +141,10 @@ theme_builtin(struct theme *theme)
 	parse_hexstr("#888888", theme->menu_separator_color);
 
 	theme->osd_window_switcher_width = 600;
-	theme->osd_window_switcher_padding = INT_MIN;
+	theme->osd_window_switcher_padding = 4;
 	theme->osd_window_switcher_item_padding_x = 10;
-	theme->osd_window_switcher_item_padding_y = 6;
+	theme->osd_window_switcher_item_padding_y = 1;
+	theme->osd_window_switcher_selection_border_width = 2;
 
 	/* inherit settings in post_processing() if not set elsewhere */
 	theme->osd_bg_color[0] = FLT_MIN;
@@ -321,6 +322,9 @@ entry(struct theme *theme, const char *key, const char *value)
 	if (match_glob(key, "osd.window-switcher.item.padding.y")) {
 		theme->osd_window_switcher_item_padding_y = atoi(value);
 	}
+	if (match_glob(key, "osd.window-switcher.selection.border.width")) {
+		theme->osd_window_switcher_selection_border_width = atoi(value);
+	}
 	if (match_glob(key, "osd.label.text.color")) {
 		parse_hexstr(value, theme->osd_label_text_color);
 	}
@@ -558,9 +562,6 @@ post_processing(struct theme *theme)
 	if (theme->osd_border_width == INT_MIN) {
 		theme->osd_border_width = theme->border_width;
 	}
-	if (theme->osd_window_switcher_padding == INT_MIN) {
-		theme->osd_window_switcher_padding = theme->osd_border_width;
-	}
 	if (theme->osd_label_text_color[0] == FLT_MIN) {
 		memcpy(theme->osd_label_text_color,
 			theme->window_active_label_text_color,
```

</details>

I could add the commit to this branch if you think its feasable.

**Comment by johanmalm** [comment]
Adding this patch sounds good.

Have you not dropped a *2 for the height calculation though?

**Comment by Consolatis** [comment]
> Have you not dropped a *2 for the height calculation though?

Yes. With it the content is not correctly centered (its always more space at the bottom than at the top).
To be honest, I didn't yet figure out why that is the case.

**Comment by johanmalm** [comment]
Regarding naming convention we ought to consider `osd.window-switcher.item.active.border.width` as the most consistent with the `menu.item` and `window` equivalents.

In terms of consistency, we should also consider the item height/width to include the border - currently it's implemented differently vertically/horizontally (my fault). 
It starts be including the item-border-width in the item-height here https://github.com/labwc/labwc/blob/b200dd2e7bbce26cf15a5b94cc5e9eae68025718/src/theme.c#L534
I can sort this :smile: but will hang on for your patch from last night.

**Comment by Consolatis** [comment]
Pushed the commit to your branch. Feel free to squash as you see fit.

**Comment by Consolatis** [comment]
LGTM

**Pull request merged**
