### PR TITLE
Implement pointer gestures

### PR DESCRIPTION
**Pull request by bi4k8**
This is pretty straightforward plumbing but also includes some minor cursor/keyboard cleanups.

### CODE REVIEW

**Comment by bi4k8** [comment]
CI seems to have failed due to HTTP 504 from gitlab.freedesktop.org.

**Comment by johanmalm** [comment]
Thanks.
Does this all relate to touch-screens? Have you been able to test it?
Do we need to add:

```
case WLR_INPUT_DEVICE_TOUCH:
		new_touch(seat, input);
		break;
```
...here:
https://github.com/labwc/labwc/blob/a837fefc80a4a77e4e0353e4b8a14ece258a642a/src/seat.c#L149

**Comment by johanmalm** [comment]
And this further down...
```
	case WLR_INPUT_DEVICE_TOUCH:
			caps |= WL_SEAT_CAPABILITY_TOUCH;
			break;
```

**Comment by bi4k8** [comment]
This is for pinch/zoom gestures on trackpad pointers, not touch screens. I've tested the pinch gesture and it seems to behave as expected, e.g. in Firefox. I don't know any software that uses other gestures.

**Comment by johanmalm** [comment]
Got it. Thanks.

**Pull request merged**
