### PR TITLE
Add RaiseLower action

### PR DESCRIPTION
**Pull request by johanmalm**

### CODE REVIEW

**Comment by johanmalm** [comment]
Would appreciate some testing. I can prove the 'Lower' bit but can't think of how to invoke the action on a window that does not currently have the keyboard focus.

**Comment by johanmalm** [comment]
Building on idea from @Consolatis 

`s/Click/Press/`
`s/Lower/RaiseLower/`

```
<mouse>
    <default />
    <context name="Close">
      <mousebind button="Left" action="Press">
        <action name="RaiseLower" />
      </mousebind>
    </context>
  </mouse>
```

**Comment by Consolatis** [comment]
Code LGTM.
Why do we need the `s/Click/Press/` for the testcase?

**Comment by johanmalm** [comment]
> Why do we need the `s/Click/Press/` for the testcase?

Not sure - just experimenting.

**Comment by stefonarch** [comment]
I can't see an use case for this. Alt-tab, iconify, toggletobottom or else does it. Maybe I'm missing something.
Anyway, wiki: https://redtide.github.io/openbox-wiki/Help/Actions/#raiselower

**Comment by johanmalm** [comment]
> I can't see an use case for this. 

On reflection, I agree.

It relies on having keyboard-focus which (for me) means that it's already raised. I'll delete it.

**Comment by wesbluemarine** [comment]
The use case is to avoid using the keyboard when there is no need. Furthermore, having the dedicated button on the windows is not exactly the same thing. [Here](https://m.youtube.com/watch?v=9F81nFwZVCc&feature=youtu.be) 's an example.

**Comment by Consolatis** [comment]
That same could be done using
- the `Lower` action to move the window to the back
- just clicking on any part of a window to `Raise` it to the top and give `Focus`.

What is missing for that workflow to work is some `Unfocus` action that ensures that the new window on top also gets keyboard focus. This PR would not have solved that though.

**Comment by johanmalm** [comment]
@wesbluemarine What Consolatis said. I just don't think a specific RaiseLower action will help achieve the use-case you describe. I think we're talking apples and pears.

**Pull request closed without merging**
