### PR TITLE
NEWS.md: update notes for 0.8.0

### PR DESCRIPTION
**Pull request by johanmalm**

### CODE REVIEW

**Comment by Consolatis** [comment]
LGTM

**Comment by jp7677** [comment]
What about adding this to fixes?
- fix tablet rotation not following output rotation https://github.com/labwc/labwc/pull/2060

**Comment by johanmalm** [comment]
> What about adding this to fixes?
> 
>     * fix tablet rotation not following output rotation [input: subscribe to tablet tool events from cursor #2060](https://github.com/labwc/labwc/pull/2060)

Thanks. Not sure how I missed that one :smile:

**Comment by tokyo4j** [comment]
LGTM

**Pull request merged**
