### PR TITLE
changes for multi-workspace window switching

### PR DESCRIPTION
**Pull request by droc12345**
These are the changes for multi-window/multi-workspace osd

This my first time doing this so I hope I did it right.

Edit to add; I haven't checked using it in reverse, but it (theoretically) should work with no problems.

### CODE REVIEW

**Comment by domo141** [comment]
I'd nitpick the use of 01/28/2024 in commit message (it looks like a date in u.s. format)

In this particular case there is not much change for confusion as there is not 28 months
in a year. but something like 2/1/2025 would be confusing (saw such a date few days ago,
both 2025-01-02 and 2024-02-01 are thursdays which added to the confusion ;)

maybe showing date there is not needed
if so I'd vote using the ISO format 2024-01-28

**Comment by ahesford** [comment]
The commit message shouldn't contain a date at all. Git metadata already records the date of a commit. The message should be a descriptive summary of the change, preferably with some location information, like

> desktop: support switching to windows in other workspaces

**Comment by droc12345** [comment]
I've messed it up, trying to change things. 
I'll delete this one and redo it properly.

Thanks for all the comments

**Comment by ahesford** [comment]
There's no need to delete this, you just need to force-push over the branch.

**Comment by droc12345** [comment]
I wasn't sure how to fix, so I just deleted and readded the patch and created a new pull #1485

**Pull request closed without merging**
