### PR TITLE
[wip] Support rc.yaml

### PR DESCRIPTION
**Pull request by johanmalm**
Tried with:

    ---
    theme:
    - name: Adwaita-light
    - cornerRadius: 2
    ...

Needs lots of testing.

### CODE REVIEW

**Comment by tokyo4j** [comment]
This is very interesting and would make labwc more attractive for new users!

However, my concern is how we should deal with XMLs like this:
```xml
      <mousebind button="W-Left" action="Press">
        <action name="Raise" />
        <action name="Move" />
      </mousebind>
```

If we were to design the config format from ground-up, something like this looks more natural:
```yaml
mousebind:
  button: W-Left
  action: Press
  actions:
    - name: Raise
    - name: Move
```

But context-based conversion like this will increase the maintenance cost and make documentation more complex.

**Comment by droc12345** [comment]
Support in addition to xml or a replacement for xml?
As as general rule, yaml is easier for a human to read, but xml is better for machine parsing.

**Comment by Consolatis** [comment]
> Support in addition to xml or a replacement for xml?

The XML config is there to stay, we prefer to not break existing setups. This is meant as an optional alternative.

**Comment by 01micko** [comment]
> The XML config is there to stay, we prefer to not break existing setups. This is meant as an optional alternative.

A lot of work for an option! 

I can't see much point in supporting 2 config syntax. Doubles (at least) the config code base for a start, not to mention documentation. Then the maintenance overhead.

I don't have a strong preference on either _but_ for one or the other I do :)

I guess, since I haven't been on IRC in a while, there has been some discussion. `yaml` certainly feels more modern than `xml` and probably would appeal to newer users.

**Comment by Consolatis** [comment]
If you look at the diff in this PR its really not that much code that is being added here and most is encapsulated in an own file. This PR converts a yaml config to a temporary XML one and then lets the usual xml parsing take over. So it doesn't really add that much complexity to the config parser backend of labwc nor really creates a maintenance issue for the future.

My personal opinion on this is:
I don't really mind to have the option to use yaml. I'd likely not use it personally though because I tend to configure things once and then run with that configuration for a long time without ever touching it again.

**Comment by johanmalm** [comment]
@tokyo4j 

You’ve hit on a sore grammar point :smile:

When I decided to use the “flat” approach at the dawn of labwc existence, I looked through the Openbox spec for conflicting attributes and child-elements but missed that one (mousebind-action).

It is an unfortunate piece of grammar, which is bad regardless of xml (because of how we parse) and yaml. We ought to discuss in a separate issue whether we change the attribute to event or something like that.

**Comment by johanmalm** [comment]
@tokyo4j I've converted `rc.xml.all` using [xml2yaml.c](https://github.com/johanmalm/yaml2xml/blob/master/xml2yaml.c) - which is just a quick hack, but hopefully enough to produce something meaningful to look at.

I have to say that apart from the mousebind-action I'm quite pleased with the grammar.

Welcome your thoughts though.


<details>
<summary>rc.yaml</summary>

```
---
- core: 
  - decoration: server
  - gap: 0
  - adaptiveSync: no
  - allowTearing: no
  - reuseOutputMode: no
  - xwaylandPersistence: no
- placement: 
  - policy: center
- theme: 
  - name: 
  - cornerRadius: 8
  - keepBorder: yes
  - dropShadows: no
  - font:
    - place: ActiveWindow
    - name: sans
    - size: 10
    - slant: normal
    - weight: normal
  - font:
    - place: InactiveWindow
    - name: sans
    - size: 10
    - slant: normal
    - weight: normal
  - font:
    - place: MenuItem
    - name: sans
    - size: 10
    - slant: normal
    - weight: normal
  - font:
    - place: OnScreenDisplay
    - name: sans
    - size: 10
    - slant: normal
    - weight: normal
- windowSwitcher:
  - show: yes
  - preview: yes
  - outlines: yes
  - allWorkspaces: no
  - fields: 
    - field:
      - content: type
      - width: 25%
    - field:
      - content: trimmed_identifier
      - width: 25%
    - field:
      - content: title
      - width: 50%
- resistance: 
  - screenEdgeStrength: 20
  - windowEdgeStrength: 20
  - unSnapThreshold: 20
- resize: 
  - popupShow: Never
  - drawContents: yes
- focus: 
  - followMouse: no
  - followMouseRequiresMovement: yes
  - raiseOnFocus: no
- snapping: 
  - range: 1
  - overlay:
    - enabled: yes
    - delay:
      - inner: 500
      - outer: 500
  - topMaximize: yes
  - notifyClient: always
- desktops: 
  - popupTime: 1000
  - names: 
    - name: Default
- keyboard: 
  - numlock: on
  - layoutScope: global
  - repeatRate: 25
  - repeatDelay: 600
  - keybind:
    - key: A-Tab
    - action:
      - name: NextWindow
  - keybind:
    - key: W-Return
    - action:
      - name: Execute
      - command: alacritty
  - keybind:
    - key: A-F3
    - action:
      - name: Execute
      - command: bemenu-run
  - keybind:
    - key: A-F4
    - action:
      - name: Close
  - keybind:
    - key: W-a
    - action:
      - name: ToggleMaximize
  - keybind:
    - key: A-Left
    - action:
      - name: MoveToEdge
      - direction: left
  - keybind:
    - key: A-Right
    - action:
      - name: MoveToEdge
      - direction: right
  - keybind:
    - key: A-Up
    - action:
      - name: MoveToEdge
      - direction: up
  - keybind:
    - key: A-Down
    - action:
      - name: MoveToEdge
      - direction: down
  - keybind:
    - key: W-Left
    - action:
      - name: SnapToEdge
      - direction: left
  - keybind:
    - key: W-Right
    - action:
      - name: SnapToEdge
      - direction: right
  - keybind:
    - key: W-Up
    - action:
      - name: SnapToEdge
      - direction: up
  - keybind:
    - key: W-Down
    - action:
      - name: SnapToEdge
      - direction: down
  - keybind:
    - key: A-Space
    - action:
      - name: ShowMenu
      - menu: client-menu
  - keybind:
    - key: XF86_AudioLowerVolume
    - action:
      - name: Execute
      - command: amixer sset Master 5%-
  - keybind:
    - key: XF86_AudioRaiseVolume
    - action:
      - name: Execute
      - command: amixer sset Master 5%+
  - keybind:
    - key: XF86_AudioMute
    - action:
      - name: Execute
      - command: amixer sset Master toggle
  - keybind:
    - key: XF86_MonBrightnessUp
    - action:
      - name: Execute
      - command: brightnessctl set +10%
  - keybind:
    - key: XF86_MonBrightnessDown
    - action:
      - name: Execute
      - command: brightnessctl set 10%-
- mouse: 
  - doubleClickTime: 500
  - scrollFactor: 1.0
  - context:
    - name: Frame
    - mousebind:
      - button: A-Left
      - action: Press
      - action:
        - name: Focus
      - action:
        - name: Raise
    - mousebind:
      - button: A-Left
      - action: Drag
      - action:
        - name: Move
    - mousebind:
      - button: A-Right
      - action: Press
      - action:
        - name: Focus
      - action:
        - name: Raise
    - mousebind:
      - button: A-Right
      - action: Drag
      - action:
        - name: Resize
  - context:
    - name: Top
    - mousebind:
      - button: Left
      - action: Drag
      - action:
        - name: Resize
  - context:
    - name: Left
    - mousebind:
      - button: Left
      - action: Drag
      - action:
        - name: Resize
  - context:
    - name: Right
    - mousebind:
      - button: Left
      - action: Drag
      - action:
        - name: Resize
  - context:
    - name: Bottom
    - mousebind:
      - button: Left
      - action: Drag
      - action:
        - name: Resize
  - context:
    - name: TRCorner
    - mousebind:
      - button: Left
      - action: Drag
      - action:
        - name: Resize
  - context:
    - name: BRCorner
    - mousebind:
      - button: Left
      - action: Drag
      - action:
        - name: Resize
  - context:
    - name: TLCorner
    - mousebind:
      - button: Left
      - action: Drag
      - action:
        - name: Resize
  - context:
    - name: BLCorner
    - mousebind:
      - button: Left
      - action: Drag
      - action:
        - name: Resize
  - context:
    - name: TitleBar
    - mousebind:
      - button: Left
      - action: Press
      - action:
        - name: Focus
      - action:
        - name: Raise
    - mousebind:
      - button: Right
      - action: Click
      - action:
        - name: Focus
      - action:
        - name: Raise
    - mousebind:
      - direction: Up
      - action: Scroll
      - action:
        - name: Unshade
      - action:
        - name: Focus
    - mousebind:
      - direction: Down
      - action: Scroll
      - action:
        - name: Unfocus
      - action:
        - name: Shade
  - context:
    - name: Title
    - mousebind:
      - button: Left
      - action: Drag
      - action:
        - name: Move
    - mousebind:
      - button: Left
      - action: DoubleClick
      - action:
        - name: ToggleMaximize
    - mousebind:
      - button: Right
      - action: Click
      - action:
        - name: ShowMenu
        - menu: client-menu
  - context:
    - name: Maximize
    - mousebind:
      - button: Left
      - action: Click
      - action:
        - name: ToggleMaximize
    - mousebind:
      - button: Right
      - action: Click
      - action:
        - name: ToggleMaximize
        - direction: horizontal
    - mousebind:
      - button: Middle
      - action: Click
      - action:
        - name: ToggleMaximize
        - direction: vertical
  - context:
    - name: WindowMenu
    - mousebind:
      - button: Left
      - action: Click
      - action:
        - name: ShowMenu
        - menu: client-menu
    - mousebind:
      - button: Right
      - action: Click
      - action:
        - name: ShowMenu
        - menu: client-menu
  - context:
    - name: Iconify
    - mousebind:
      - button: Left
      - action: Click
      - action:
        - name: Iconify
  - context:
    - name: Close
    - mousebind:
      - button: Left
      - action: Click
      - action:
        - name: Close
  - context:
    - name: Client
    - mousebind:
      - button: Left
      - action: Press
      - action:
        - name: Focus
      - action:
        - name: Raise
    - mousebind:
      - button: Middle
      - action: Press
      - action:
        - name: Focus
      - action:
        - name: Raise
    - mousebind:
      - button: Right
      - action: Press
      - action:
        - name: Focus
      - action:
        - name: Raise
  - context:
    - name: Root
    - mousebind:
      - button: Left
      - action: Press
      - action:
        - name: ShowMenu
        - menu: root-menu
    - mousebind:
      - button: Right
      - action: Press
      - action:
        - name: ShowMenu
        - menu: root-menu
    - mousebind:
      - button: Middle
      - action: Press
      - action:
        - name: ShowMenu
        - menu: root-menu
    - mousebind:
      - direction: Up
      - action: Scroll
      - action:
        - name: GoToDesktop
        - to: left
        - wrap: yes
    - mousebind:
      - direction: Down
      - action: Scroll
      - action:
        - name: GoToDesktop
        - to: right
        - wrap: yes
- touch: 
- tablet:
  - rotate: 0
  - mouseEmulation: no
  - area:
    - top: 0.0
    - left: 0.0
    - width: 0.0
    - height: 0.0
  - map:
    - button: Tip
    - to: Left
  - map:
    - button: Stylus
    - to: Right
  - map:
    - button: Stylus2
    - to: Middle
- tabletTool:
  - motion: absolute
  - relativeMotionSensitivity: 1.0
- libinput: 
  - device:
    - category: default
    - naturalScroll: 
    - leftHanded: 
    - pointerSpeed: 
    - accelProfile: 
    - tap: yes
    - tapButtonMap: 
    - tapAndDrag: 
    - dragLock: 
    - middleEmulation: 
    - disableWhileTyping: 
    - clickMethod: 
    - sendEventsMode: 
    - calibrationMatrix: 
- menu: 
  - ignoreButtonReleasePeriod: 250
- magnifier: 
  - width: 400
  - height: 400
  - initScale: 2.0
  - increment: 0.2
  - useFilter: true
...
```

</details>

**Comment by johanmalm** [comment]
My current `rc.yaml` :smile:

<details>
<summary>rc.yaml</summary>

```YAML
---
core: 
- gap: 5
placement: 
- policy: Cascade
theme: 
- name: Adwaita-light
- cornerRadius: 5
- font: 
  - name: Ubuntu
  - size: 10
- dropShadows: yes
windowSwitcher: 
- allWorkspaces: yes
desktops: 
- names: 
  - name: 1
  - name: 2
  - name: 3
menu: 
- hideDelay: 2000
keyboard: 
- default: 
- layoutScope: window
- keybind:
  - key: W-l
  - name.action: Execute
  - command.action: swaylock -c 000000
- keybind:
  - key: C-A-t
  - name.action: Execute
  - command.action: foot
- keybind:
  - key: W-q
  - action:
    - name: CycleNearRegion
    - region: foo
- keybind:
  - key: Super_L
  - onRelease: yes
  - name.action: ShowMenu
  - menu.action: root-menu
- keybind:
  - key: W-v
  - name.action: SetDecorations
  - decorations.action: border
- keybind:
  - key: W-z
  - name.action: Execute
  - command.action: rofi -show drun
- keybind:
  - key: C-W-d
  - name.action: Execute
  - command.action: dmenu_run
- keybind:
  - key: C-W-t
  - name.action: Execute
  - command.action: sakura
- keybind:
  - key: C-W-y
  - name.action: Execute
  - command.action: xterm
- keybind:
  - key: W-F7
  - name.action: Execute
  - command.action: wf-recorder --output eDP-1
- keybind:
  - key: W-F8
  - name.action: Execute
  - command.action: killall SIGINT wf-recorder
- keybind:
  - key: C-Escape
  - name.action: ShowMenu
  - menu.action: pipe-test
- keybind:
  - key: W-F10
  - name.action: Debug
- keybind:
  - key: W-F11
  - name.action: ToggleDecorations
- keybind:
  - key: F12
  - name.action: ToggleKeybinds
- keybind:
  - key: S-A-Tab
  - name.action: PreviousWindow
- keybind:
  - key: W-j
  - action:
    - name: NextWindow
- keybind:
  - key: W-k
  - action:
    - name: PreviousWindow
- keybind:
  - key: W-Left
  - action:
    - name: MoveToEdge
    - direction: left
    - snapWindows: true
- keybind:
  - key: W-Right
  - action:
    - name: MoveToEdge
    - direction: right
    - snapWindows: true
- keybind:
  - key: W-Up
  - action:
    - name: MoveToEdge
    - direction: up
    - snapWindows: true
- keybind:
  - key: W-Down
  - action:
    - name: MoveToEdge
    - direction: down
    - snapWindows: true
- keybind:
  - key: W-S-Left
  - action:
    - name: ShrinkToEdge
    - direction: left
- keybind:
  - key: W-S-Right
  - action:
    - name: GrowToEdge
    - direction: right
- keybind:
  - key: W-S-Up
  - action:
    - name: ShrinkToEdge
    - direction: up
- keybind:
  - key: W-S-Down
  - action:
    - name: GrowToEdge
    - direction: down
- keybind:
  - key: C-W-Left
  - action:
    - name: SnapToEdge
    - direction: left
- keybind:
  - key: C-W-Right
  - action:
    - name: SnapToEdge
    - direction: right
- keybind:
  - key: C-W-Up
  - action:
    - name: SnapToEdge
    - direction: up
- keybind:
  - key: C-W-Down
  - action:
    - name: SnapToEdge
    - direction: down
- keybind:
  - key: A-Right
- keybind:
  - key: A-Left
- keybind:
  - key: A-Up
- keybind:
  - key: A-Down
- keybind:
  - key: Print
  - action:
    - name: Execute
    - command: sh -c 'grim -g "$(slurp)"'
mouse: 
- default: 
- context:
  - name: Root
  - mousebind:
    - button: Left
    - action: Press
    - action:
      - name: Unfocus
- context:
  - name: Top
  - mousebind:
    - button: Left
    - action: DoubleClick
    - action:
      - name: ToggleMaximize
      - direction: vertical
- context:
  - name: Bottom
  - mousebind:
    - button: Left
    - action: DoubleClick
    - action:
      - name: ToggleMaximize
      - direction: vertical
- context:
  - name: Left
  - mousebind:
    - button: Left
    - action: DoubleClick
    - action:
      - name: ToggleMaximize
      - direction: horizontal
- context:
  - name: Right
  - mousebind:
    - button: Left
    - action: DoubleClick
    - action:
      - name: ToggleMaximize
      - direction: horizontal
- context:
  - name: All
  - mousebind:
    - direction: W-Up
    - action: Scroll
    - action:
      - name: ZoomIn
  - mousebind:
    - direction: W-Down
    - action: Scroll
    - action:
      - name: ZoomOut
libinput: 
- device: 
  - tapAndDrag: yes
  - dragLock: yes
  - naturalScroll: no
regions: 
- region:
  - name: foo
  - x: 0%
  - y: 0%
  - height: 100%
  - width: 50%
- region:
  - name: top-left
  - x: 0%
  - y: 0%
  - height: 50%
  - width: 50%
- region:
  - name: top
  - x: 0%
  - y: 0%
  - height: 70%
  - width: 100%
- region:
  - name: top-right
  - x: 50%
  - y: 0%
  - height: 50%
  - width: 50%
- region:
  - name: left
  - x: 0%
  - y: 0%
  - height: 100%
  - width: 50%
- region:
  - name: center
  - x: 10%
  - y: 5%
  - height: 90%
  - width: 80%
- region:
  - name: right
  - x: 50%
  - y: 0%
  - height: 100%
  - width: 50%
- region:
  - name: bottom-left
  - x: 0%
  - y: 50%
  - height: 50%
  - width: 50%
- region:
  - name: bottom
  - x: 0%
  - y: 50%
  - height: 70%
  - width: 100%
- region:
  - name: bottom-right
  - x: 50%
  - y: 50%
  - height: 50%
  - width: 50%
- region:
  - name: panel
  - x: 0%
  - y: 0%
  - height: 70%
  - width: 50%
- region:
  - name: notifications
  - x: 70%
  - y: 0%
  - height: 50%
  - width: 50%
- region:
  - name: runner
  - x: 40%
  - y: 20%
  - height: 1%
  - width: 20%
...
```

</details>

**Comment by tokyo4j** [comment]
Hmm... I understand we need to express every XML node as an array in YAML in order to keep compatibility, but it looks too biased toward XML and I'm afraid it confuses users.

For example, when I tried following YAML without preceding hyphens:
```yaml
desktops:
  number: 2
placement:
  policy: cascade
```
I get following error:
```
Entity: line 4: parser error : StartTag: invalid element name
<2>placement</2>
 ^
Entity: line 4: parser error : expected '>'
<2>placement</2>
              ^
Entity: line 4: parser error : Opening and ending tag mismatch: labwc_config line 2 and unparsable
<2>placement</2>
              ^
00:00:00.000 [../src/config/rcxml.c:1219] error parsing config file
```

Also, the need for the repeated use of `keybind`/`mousebind`/`region` doesn't look natural in YAML.

Now I'm feeling guilty for what I said in IRC. I didn't meant to criticize labwc's decision to use XML, but I just wanted to say it's sad to see some people don't try labwc because they hate XML. Actually I don't think XML is that bad if we use the shortened syntax or labwc-tweaks.

Therefore, I think for now we should keep supporting only XML and focus on labwc-tweaks or better documentation.

Another approach to support YAML and keep compatibility without syntax weirdness or more maintenance cost is:
- Stop supporting new config entries in XML and only support them in YAML
- Convert old XML config into YAML like https://github.com/labwc/labwc/pull/2077#issuecomment-2287220008, restructuring its format
- Also provide a CUI tool to convert old XML into YAML

But I'm not sure it's possible. At least it would not be our priority.

**Comment by Consolatis** [comment]
Another alternative is to write some additional config backend for yaml that just fills `struct rc`, that is our abstraction already. However that would then indeed mean that we now have to keep the config backends in sync which doesn't sound great.

I don't think that we should get rid of the XML config any time soon because that is what labwc started with and thus what is the most familiar to the existing user base. Additionally, labwc is being strongly inspired by Openbox (and marketed as such) and removing the xml config doesn't feel right to me. Then there is also the aspect of stability and introducing no regressions, removing a config backend is a very breaking change, even if we would automatically convert it to yaml. The fact that some config options would then only work with yaml alone is a breaking change because users then have to get used to a new config format.

If we can get the approach taken in this PR working in a more YAML way (even if it requires some more logic when translating from yaml to xml) then great. No objections to additionally support YAML. If we don't get it working and have to keep two config backends in sync or deprecate the XML backend I'd say its just not worth it and we should stick to XML only.

Absolutely agree that providing some GUI frontend to configure everything is a good option, some people really don't want to mess with any text configuration, regardless of it being XML, YAML, .ini or whatever else.

**Comment by johanmalm** [comment]
> Hmm... I understand we need to express every XML node as an array in YAML.

We probably don’t.

Did you see this? https://github.com/johanmalm/yaml2xml

It was a super quick hack to evaluate feasibility.  I simply just saw that libyaml was widely packaged (which was a prerequisite for even having a go) and decided to have a play. 

I just took the first best yaml config I could find, but suspect we could parse without those hyphens (for arrays)

> For example, when I tried following YAML without preceding hyphens:
> 
> ```yaml
> desktops:
>   number: 2
> placement:
>   policy: cascade
> ```

How about we discuss grammar for a bit and then I try to implement. So far I’ve only spent an hour each on the two CLI tools, and I quite enjoy experimenting a bit.

If nothing else it’ll leave us with a CLI tool that people can use to convert YAML to XML for labwc.

> Also, the need for the repeated use of `keybind`/`mousebind`/`region` doesn't look natural in YAML.

Ah, so how would you write it natively in YAML? If we define that position we can ponder if we can convert it.

> Now I'm feeling guilty for what I said in IRC.

Don’t. It’s not a problem.

> it's sad to see some people don't try labwc because they hate XML.

Agree. You’re not the first one to have said it. Many have criticised the choice. Now, whilst I personally quite like XML, the fact that many don’t should make us consider this patch. Plugging it in to labwc obviously turned out to be very easy as a stand-alone module.

So I think the question to answer is if we can find an acceptable YAML grammar that’s translatable to the extant XML-nodename grammar. I think the CLI tool is the best starting point to evaluate/experiment further.

> Therefore, I think for now we should keep supporting only XML and focus on labwc-tweaks or better documentation.

We should improve the documentation with XML examples at the start of each section just like Openbox did.

> Another approach to support YAML and keep compatibility without syntax weirdness or more maintenance cost is:

**Comment by tokyo4j** [comment]
>> Hmm... I understand we need to express every XML node as an array in YAML.
>
> We probably don’t.

Yeah, I was wrong. I agree that it won't be a technical limitation.

> Ah, so how would you write it natively in YAML? If we define that position we can ponder if we can convert 

I mean something like this:

<details><summary>rc.yaml.all</summary>

```yaml
theme:
  fonts:
    - place: ActiveWindow
      size: 10
      slant: normal
      weight: normal
    - place: InactiveWindow
      size: 10
      slant: normal
      weight: normal
windowSwitcher:
  show: yes
  preview: yes
  fields:
    - content: type
      width: 25%
    - content: trimmed_identifier
      width: 25%
    - content: title
      width: 50%
desktops:
  popupTime: 1000
  names:
    - Workspace 1
    - Workspace 2
    - Workspace 3
    - Workspace 4
regions:
  - name: top-left
    x: 0%
    y: 0%
    height: 50%
    width: 50%
  - name: top-right
    x: 50%
    y: 0%
    height: 50%
    width: 50%
keyboard:
  repeatRate: 25
  repeatDelay: 600
  keybinds:
    - key: A-Tab
      actions:
        - name: NextWindow
    - key: W-Return
      actions:
        - name: Execute
          command: alacritty
mouse:
  doubleClickTime: 500
  scrollFactor: 1.0
  contexts:
    - name: Frame
      mousebinds:
        - button: A-left
          action: Press
          actions:
          - name: Focus
          - name: Raise
        - button: A-left
          action: Drag
          actions:
          - name: Move
    - name: Top
      mousebinds:
        - button: Left
          action: Drag
          actions:
          - name: Resize
touchDevices:
  - deviceName: ""
    mapToOutput: ""
  - deviceName:
    mapToOutput: ""
libinput:
  devices:
    - category: touchpad
      naturalScroll: yes
      tapAndDrag: no
    - category: non-touch
      naturalScroll: no
windowRules:
  - idenifier: lxqt-panel
    matchOnce: true
    skipTaskbar: yes
    actions:
      - name: MoveTo
        x: 0
        y: 0
      - name: ToggleAlwaysOnTop
  - title: pcmanfm-desktop
    skipTaskbar: yes
    skipWindowSwitcher: yes
    fixedPosition: yes
    actions:
      - name: MoveTo
        x: 0
        y: 0
      - name: ToggleAlwaysOnBottom
```

</details>

By utilizing arrays, repeated uses of `keybind`/`mousebind`/`region` (and more) can be omitted. I believe this is how config files in key-value markup languages should be written. I don't know how complicated the conversion will be though.

**Comment by tokyo4j** [comment]
I made a [prototype](https://github.com/tokyo4j/yaml2xml) that converts:
```yaml
keyboard:
  keybind:
    - key: A-F4
      action:
        - name: Close
    - key: W-s
      action:
        - name: Execute
          command: Alacritty
```
into:
```xml
  <keyboard>
    <keybind>
      <key>A-F4</key>
      <action>
        <name>Close</name>
      </action>
    </keybind>
    <keybind>
      <key>W-s</key>
      <action>
        <name>Execute</name>
        <command>Alacritty</command>
      </action>
    </keybind>
  </keyboard>
```

Honestly I prefer "keybinds" to "keybind", but this algorithm enables conversion without looking into key/value names and I think this hits the sweet spot between beauty and complexity.

**Comment by johanmalm** [comment]
> I made a [prototype](https://github.com/tokyo4j/yaml2xml) that converts:

Hey, that looks amazing. A lot more sane than my attempt.

How about we add some tests and give it thorough going over.

> Honestly I prefer "keybinds" to "keybind", but this algorithm enables conversion without looking into key/value names and I think this hits the sweet spot between beauty and complexity.

Well, I'm not against coming up with a rule-set to subtle change the grammar whilst we're at it. Like mapping `keybinds`->`keybind` etc. I do agree, plural is nicer.

**Comment by tokyo4j** [comment]
> How about we add some tests and give it thorough going over.

Adding tests sounds nice, but I'm not sure how we should do it. Do you mean something like #1099?

> > Honestly I prefer "keybinds" to "keybind", but this algorithm enables conversion without looking into key/value names and I think this hits the sweet spot between beauty and complexity.
> 
> Well, I'm not against coming up with a rule-set to subtle change the grammar whilst we're at it. Like mapping `keybinds`->`keybind` etc. I do agree, plural is nicer.

Alright. I'm not strongly against it either.

Other suggestions about the YAML->XML mapping rule are:

- `<windowSwitcher><fields>` -> `<windowSwitcher><fields><field>`
- `<regions>` -> `<regions><region>`
- `<windowRules>` -> `<windowRules><windowRule>`
- `<libinput>` -> `<libinput><device>`

As YAML doesn't need wrapping node for each element in an array, elements like `<field>` are redundant and should be removed. I think these are more important than singular vs plural, because redundant nodes mean more indentations and hurt readability.

I'm thinking of opening another PR that implements these rules and evaluating its implementation & documentation complexity.

**Comment by johanmalm** [comment]
> Adding tests sounds nice, but I'm not sure how we should do it. Do you mean something like #1099?

Either something like this: 
  - https://github.com/labwc/labwc-menu-generator/tree/master/t

Although, for what we're doing (fundamentally `yaml2xml < input > actual` and then compare `actual` with a predefined `expect` I quite like https://github.com/felipec/sharness (which is a modularized version of git's test framework). The nice thing about sharness is that it's designed for shell constructs, and on failure you get a trash-directory so that you can manually compare actual with expected.

I can do a PR with a sharness demo to evaluate if you want. Although it'll probably have to be tomorrow.

Shall I pull the commits from your branch?

> Other suggestions about the YAML->XML mapping rule are:
> 
>     * `<windowSwitcher><fields>` -> `<windowSwitcher><fields><field>`
> 
>     * `<regions>` -> `<regions><region>`
> 
>     * `<windowRules>` -> `<windowRules><windowRule>`
> 
>     * `<libinput>` -> `<libinput><device>`
> 
> 
> As YAML doesn't need wrapping node for each element in an array, elements like `<field>` are redundant and should be removed. I think these are more important than singular vs plural, because redundant nodes mean more indentations and hurt readability.

I like this. Feels like it's better to get it right whilst we're at it. 

I think user-experience ought to carry higher importance than code complexity for this (because I don't think that some grammar-mapping would actually be that hard to maintain/understand).

> I'm thinking of opening another PR that implements these rules and evaluating its implementation & documentation complexity.

Shall I merge what you've done so far?

**Comment by johanmalm** [comment]
Yes - recursion is nice for parsing.

Your tokyo4j:support-yaml branch looks fantastic.

How do you think we should proceed?

1. Review/test your tokyo4j:support-yaml (and we can add some unit tests to it later directly in the labwc repo)
2. Carry on building confidence in the yaml2xml repos?

I had thought (2) was a nice, steady approach, but having just seen your `tokyo4j:support-yaml` it feels pretty close and I'm happy to go down that route.

**Comment by tokyo4j** [comment]
>     1. Review/test your tokyo4j:support-yaml (and we can add some unit tests to it later directly in the labwc repo)
> 
>     2. Carry on building confidence in the yaml2xml repos?
> 
> I had thought (2) was a nice, steady approach, but having just seen your `tokyo4j:support-yaml` it feels pretty close and I'm happy to go down that route.

I prefer (1). As a person who likes how Rust/Zig allows us to embed unit tests in the source code, I believe tests should be managed in the same repo as the main source code.

I can open another PR, but feel free to pull my changes in this PR (with `helped by: @toyko4j` in the commit message) and continue working on documentation or adding tests. I have some PRs to work on (#2052 #2057), so I want to focus on those first.

**Comment by johanmalm** [comment]
> EDIT: Sorry for the confusion talked about in IRC. I once pushed the edited `labwc-config.5.scd` and `docs/rc.yaml`. I removed them because I'm so lazy to make my own PR and wanted to delegate this task to malm. Now I've decided to make another PR with the documentations. But as I said I have some other pending PRs, so I'll do it later (I believe it's within a week).

A new PR sounds a good plan. When you open it, I'll close this one.

Would it be useful to have a test-framework + a `buf_add_fmt()` to help this?

**Comment by tokyo4j** [comment]
> Would it be useful to have a test-framework + a buf_add_fmt() to help this?

Oh sorry! I somehow overlooked your comment. Your #2093 is really helpful.

**Comment by ahesford** [comment]
Repeating [my comment on the other PR](https://github.com/labwc/labwc/pull/2106#issuecomment-2306951238) for completeness:

> Although I would prefer YAML to XML for all labwc input files, I think this should only be merged if we intend to deprecate and eventually remove XML support. Retaining eternal support for both formats will increase maintenance burden and user confusion.

**Comment by johanmalm** [comment]
Overtaken by #2106 and https://github.com/johanmalm/yaml2xml

**Pull request closed without merging**
