### PR TITLE
tearing: add 'always' which by default enables tearing for all windows

### PR DESCRIPTION
**Pull request by Consolatis**
Closes
- #2272

### CODE REVIEW

**Comment by Consolatis** [comment]
Without the x11 unmanaged surfaces being handles this PR does not what it says. If you want to use it without the logging you can do `git revert 8de8fed257db16cca01d288b8e622c88a41ec71e` before rebuilding.

**Comment by Consolatis** [comment]
I've pushed a fix for unmanaged surfaces in combination with the `always` config. Testing welcome, logs are not needed but can be used to verify that labwc is requesting tearing correctly.

**Comment by Consolatis** [comment]
One thing I missed when working on this is that `server->active_view` isn't updated when unmanaged surfaces get focus which is why it sometimes works and other times it does not.

I don't use tearing and don't have that much motivation to dive deeper into a proper solution to this issue. If somebody wants to take this over feel free.

**Comment by zeusgoose** [comment]
greetings. i reworked this to workaround unmanaged fullscreen x11 windows not tearing. this is my second week of learning to code. please forgive my ignorance. 
the main problem i had with the original patch was fullscreen unmanaged xwayland surfaces not honoring anything other than "hints". this works around that by forcing tearing on non-fullscreen windows with the always option. probably not the proper solution but for my needs it works. needs testing with regular fullscreen wayland surfaces. feedback if its worthy of a pull request would be most appreciated

```udiff
Subject: [PATCH 1/4] add always to labwc-config.5.scd

---
 docs/labwc-config.5.scd | 10 ++++++++--
 1 file changed, 8 insertions(+), 2 deletions(-)

diff --git a/docs/labwc-config.5.scd b/docs/labwc-config.5.scd
index 258eaa038..6122bd653 100644
--- a/docs/labwc-config.5.scd
+++ b/docs/labwc-config.5.scd
@@ -192,18 +192,24 @@ this is for compatibility with Openbox.
 	*fullscreen* enables adaptive sync whenever a window is in fullscreen
 	mode.
 
-*<core><allowTearing>* [yes|no|fullscreen|fullscreenForced]
+*<core><allowTearing>* [yes|no|fullscreen|fullscreenForced|always]
 	Allow tearing to reduce input lag. Default is no.
 
 	*yes* allows tearing if requested by the active window.
 
+	*no* tearing is disabled completely.
+
 	*fullscreen* allows tearing if requested by the active window, but
 	only when the window is in fullscreen mode.
 
 	*fullscreenForced* enables tearing whenever the active window is in
 	fullscreen mode, whether or not the application has requested tearing.
 
-	Use the *ToggleTearing* action for forcefully enable tearing.
+	*always* enable tearing for all windows by default, ignoring application
+	requests. The ToggleTearing action may be used to disable tearing.
+
+	Use the *ToggleTearing* action to forcefully enable / disable tearing
+	for the active window. Has no effect when allowTearing is set to no.
 
 	Note: Enabling this option with atomic mode setting is experimental. If
 	you experience undesirable side effects when tearing is allowed,

From 86219ce7532871bdf56ed752e876a9216cf5eb11 Mon Sep 17 00:00:00 2001
From: zeusgoose <193160247+zeusgoose@users.noreply.github.com>
Date: Sat, 12 Apr 2025 16:29:26 +0000
Subject: [PATCH 2/4] add LAB_TEARING_ALWAYS to rcxml.h

---
 include/config/rcxml.h | 1 +
 1 file changed, 1 insertion(+)

diff --git a/include/config/rcxml.h b/include/config/rcxml.h
index 3867618ee..44ebe6762 100644
--- a/include/config/rcxml.h
+++ b/include/config/rcxml.h
@@ -37,6 +37,7 @@ enum tearing_mode {
 	LAB_TEARING_ENABLED,
 	LAB_TEARING_FULLSCREEN,
 	LAB_TEARING_FULLSCREEN_FORCED,
+	LAB_TEARING_ALWAYS,
 };
 
 enum tiling_events_mode {

From 304472288702e8c5a24e9dbb7648e82173444515 Mon Sep 17 00:00:00 2001
From: zeusgoose <193160247+zeusgoose@users.noreply.github.com>
Date: Sat, 12 Apr 2025 16:33:08 +0000
Subject: [PATCH 3/4] add always var to rcxml.c

---
 src/config/rcxml.c | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/src/config/rcxml.c b/src/config/rcxml.c
index 419e8daa3..fb92a2d2f 100644
--- a/src/config/rcxml.c
+++ b/src/config/rcxml.c
@@ -926,6 +926,8 @@ set_tearing_mode(const char *str, enum tearing_mode *variable)
 		*variable = LAB_TEARING_FULLSCREEN;
 	} else if (!strcasecmp(str, "fullscreenForced")) {
 		*variable = LAB_TEARING_FULLSCREEN_FORCED;
+	} else if (!strcasecmp(str, "always")) {
+		*variable = LAB_TEARING_ALWAYS;
 	} else if (parse_bool(str, -1) == 1) {
 		*variable = LAB_TEARING_ENABLED;
 	} else {

From f228b6deae2ab1659d808fe81c88061391025340 Mon Sep 17 00:00:00 2001
From: zeusgoose <193160247+zeusgoose@users.noreply.github.com>
Date: Sat, 12 Apr 2025 16:38:49 +0000
Subject: [PATCH 4/4] add always to output.c

---
 src/output.c | 18 ++++++++++++++----
 1 file changed, 14 insertions(+), 4 deletions(-)

diff --git a/src/output.c b/src/output.c
index e72d14cf9..25b6a33b1 100644
--- a/src/output.c
+++ b/src/output.c
@@ -50,8 +50,15 @@ output_get_tearing_allowance(struct output *output)
 		return false;
 	}
 
+	/* force tearing on non-fullscreen windows when always */
+	if (rc.allow_tearing == LAB_TEARING_ALWAYS) {
+		if (!view->fullscreen) {
+		return true;
+		}
+	}
+
 	/* allow tearing for any window when requested or forced */
-	if (rc.allow_tearing == LAB_TEARING_ENABLED) {
+	if (rc.allow_tearing == LAB_TEARING_ENABLED  || rc.allow_tearing == LAB_TEARING_ALWAYS) {
 		if (view->force_tearing == LAB_STATE_UNSPECIFIED) {
 			return view->tearing_hint;
 		} else {
@@ -60,14 +67,17 @@ output_get_tearing_allowance(struct output *output)
 	}
 
 	/* remaining tearing options apply only to full-screen windows */
-	if (!view->fullscreen) {
+	if (rc.allow_tearing != LAB_TEARING_ALWAYS) {
+		if (!view->fullscreen) {
 		return false;
+		}
 	}
 
 	if (view->force_tearing == LAB_STATE_UNSPECIFIED) {
-		/* honor the tearing hint or the fullscreen-force preference */
+		/* honor the tearing hint or the fullscreen-force and always preferences */
 		return view->tearing_hint ||
-			rc.allow_tearing == LAB_TEARING_FULLSCREEN_FORCED;
+			rc.allow_tearing == LAB_TEARING_FULLSCREEN_FORCED ||
+			rc.allow_tearing == LAB_TEARING_ALWAYS;
 	}
 
 	/* honor tearing as requested by action */

```

**Comment by johanmalm** [comment]
Suggest opening a new PR for this if you're happy to. 

I don't use tearing myself, but it feels like there is a use-case here.

I think we need to debate the logic + rationale between a few of us, but it's a lot easier/cleaner with a new PR. I don't think there will be any resistance to this in principle.

**Comment by zeusgoose** [comment]
Sorry for bumping this again, but I figure I'd report my findings. I recently rebased the original patch against master and drove it for a while. The following occurs with `always`: 
- Mouse input latency is noticeably worse. 
- Cursor shape doesn't get updated (moving across a window edge, the cursor changes to the resize edge shape and stays like that).
- Cursor disappears when hovering over videos in firefox.

I've concluded the `always` option is going to be way too much work. The best bet for users is using the `yes` or fullscreen options and toggling when needed. Apologies for the noise. God bless

**Pull request closed without merging**
