### PR TITLE
 interactive: allow moving horizontally/vertically maximized window

### LINKED ISSUE #1521: Window unmaximizes upon movement
I don't know if this behavior is intended, I hope not.
Issue:
Maximize a window - try to move it - it unmaximizes.

Expected behavior: if window is maximized in only 1 dimension - it's movement is locked to only the opposite dimension. If it is fully maximized: the window is unmovable. Of course in both cases it keeps the maximized status.

It is useful for example for a workflow with tall and narrow terminal windows.

This is also the openbox behavior.

### PR DESCRIPTION
**Pull request by tokyo4j**
Fixes #1521

Applies drag resistance unidirectionally for horizontally/vertically maximized windows, allowing them to be dragged without being untiled immediately.

While dragging a horizontally/vertically maximized window, edge/region snapping is disabled to prevent unintentional snapping and overlays.

The first commit stops unshading maximized/tiled views at the start of interactive move as it did't seem to be useful and caused flicker.

This PR also includes some refactoring to simplify the logic.

I'm totally fine delaying this PR after the next release. But I want to move forward the discussion below:

## Discussion

As I said in IRC yesterday, I'm thinking of changing `<snapping><dragResistance>` to something like `<resistance><snapOffThreshold>` (or maybe `<resistance><unSnapThreshold>`) as `<resistance>` feels more suitable place for this setting. But while testing this PR, I started to think that it may be also useful to have another setting to configure the resistance for horizontally/vertically maximized windows as it requires more carefulness to drag them in one direction without un-tiling them.

What I came up with are:
- `<resistance><snapOffThreshold>` - for normally maximized or tiled windows
- `<resistance><snapOffThresholdHVMaximized>` - for horizontally/vertically maximized windows

Any ideas?

### CODE REVIEW

**Comment by johanmalm** [comment]
I really like `<resistance><unSnapThreshold>` but am fine with either. It would be good to get that change in before the release.

Why do we need a different setting for the uni-directional maximized case? Is it because we're likely to need a greater threshold because people are unlikely to be able to drag vertically/horizontally in a "straight" line (i.e. straight within a tolerance plus/minus `unSnapThreshold`?

**Comment by tokyo4j** [comment]
> I really like <resistance><unSnapThreshold> but am fine with either. It would be good to get that change in before the release.

Opened #2056.

> Is it because we're likely to need a greater threshold because people are unlikely to be able to drag vertically/horizontally in a "straight" line (i.e. straight within a tolerance plus/minus unSnapThreshold?

Yes. Not a strong preference though, as I don't usually unidirectionally maximize windows.

Maybe just using `<resistance><unSnapThreshold>` for normally/vertically/horizontally maximized windows is enough. KWin for example has a common threshold of (screen size) / 16 ([ref](https://github.com/KDE/kwin/blob/df9f8f8346b5b7645578e37365dabb1a7b02ca5a/src/workspace.cpp#L2642)).

**Comment by johanmalm** [comment]
Is this one ready for final review?

**Comment by tokyo4j** [comment]
> Is this one ready for final review?

I'll do some refactors and ensure I don't break anything. I'll ping and mark this PR as ready for review when I finish it.

**Comment by tokyo4j** [comment]
@johanmalm Now ready for review!

**Comment by johanmalm** [comment]
Documentation + `rc.xml.all` missing.

Have tested. Works really well :smile:

Not looked through code yet (other than spotting that docs were missing).

**Comment by Consolatis** [comment]
Tested and works great. Thanks!

**Pull request merged**
