### PR TITLE
docs: add description for new theme buttons 'shade' and desk'

### LINKED ISSUE #2113: document new ssd buttons
A description in `labwc-theme.5` is needed for the new 'desk' and 'shade' buttons; `xbm`, `png` and `svg`

### PR DESCRIPTION
**Pull request by 01micko**
fixes #2113

### CODE REVIEW

**Comment by 01micko** [comment]
Making WIP because 
- labwc ootb doesn't have the additional icons by default
- they are supported so maybe they should go in the first section?

RFC

**Comment by ahesford** [comment]
This should also wait for a resolution of #2112, so that we have consistent terminology.

What do you mean by "doesn't have the additional icons by default"?

**Comment by 01micko** [comment]
> What do you mean by "doesn't have the additional icons by default"?

When I switched to latest master the defaults were the same (maybe because of my rc.xml), that's all. Just was'nt sure to put them in the first or second stanza (for xbm). Happy to change if necessary.

I'm happy to wait. Just added the full set for svg/png and tested working well.

**Comment by 01micko** [comment]
Added some svg icons for testing if anyone likes. 

https://github.com/labwc/labwc-artwork/pull/19

**Comment by Consolatis** [comment]
Thanks!

**Comment by 01micko** [comment]
Always a pleasure :)

**Pull request merged**
