### PR TITLE
tearing: add fullscreen option

### PR DESCRIPTION
**Pull request by Consolatis**
If set, labwc will try to automatically enable tearing for fullscreen applications.

Fixes:
- #1557

---
@ahesford @Ph42oN review appreciated.

### CODE REVIEW

**Comment by Consolatis** [comment]
Technically I guess we should actually check for a tearing hint by the application and only if there is none allow tearing for fullscreen. Otherwise applications don't have a chance to disable tearing when fullscreen (end enabled by the user).

That would require `view->tearing_hint` to become some `yes|no|unspec` enum.

**Comment by ahesford** [comment]
If we're going to respect a no-trading hint from the client, I don't think we should further complicate the interface by splitting the fullscreen option in two. If users wish to override the client hint, they can just use the `ToggleTearing` action.

**Comment by Faugus** [comment]
I found a problem. If I play a video with `mpv` on fullscreen, it speeds up the playback.

**Comment by Consolatis** [comment]
Automatically detecting a fullscreen game vs a fullscreen video player doesn't sound that easy. Not sure if we can make the new `fullscreen` work for both. If we end up respecting application / user configuration via `ToggleTearing` even if configured for `fullscreen`, the user could at least manually disable tearing again for cases likes mpv.

**Comment by jp7677** [comment]
Imho video players should set the no-tearing hint (may be mpv already does that, I don’t know), together with https://github.com/labwc/labwc/pull/1568#issuecomment-1968095678 should disable tearing for those cases.

**Comment by Faugus** [comment]
This option `video-sync=display-resample` in MPV's config file with `allowTearing` was causing the issue.
I set this a long time ago and I didn't remember.

Sorry.

**Comment by Consolatis** [comment]
> This option `video-sync=display-resample` in MPV's config file with `allowTearing` was causing the issue. I set this a long time ago and I didn't remember.
> 
> Sorry.

No worries, thanks for mentioning the underlying reason.

Changed the PR to prefer client state (either set by the client or via `ToggleTearing`) over fullscreen.

**Comment by Faugus** [comment]
If you want me to do any tests, just let me know.

**Comment by Consolatis** [comment]
Feel free to test the current state of the PR. What should happen now is that with `<allowTearing>fullscreen</allowTearing>`
- tearing should be automatically enabled when in fullscreen
- when then using `ToggleTearing` you should still be able to disable / re-enable tearing while in fullscreen

**Comment by Faugus** [comment]
On `mpv` with `video-sync=display-resample` in the config file, it works.
But it's not working with games.
If I toggle it, it breaks the gamepad compatibility like before, but it doesn't seems to turn on the `allowTearing`.
The game looks like the `allowTearing` is always off, cause I don't see the jittering.

**Comment by Ph42oN** [comment]
Using this branch, tearing does not seem to work at all in [VRRTest](https://github.com/Nixola/VRRTest). This breaks enabling it even with ToggleTearing that used to work. But it continues to work in games that request tearing. I think it requests to not tear, and i think we should have way to override that, in previous patch i made this work by setting tearing_hint only if it is to enable it.

**Review by Ph42oN — COMMENTED** [review]
I think this would be simple way to make ToggleTearing override it.
```diff
diff --git a/include/view.h b/include/view.h
index c3363623..c4bfca2f 100644
--- a/include/view.h
+++ b/include/view.h
@@ -170,6 +170,7 @@ struct view {
 	enum view_axis maximized;
 	bool fullscreen;
 	enum three_state tearing_hint;
+	bool tearing_override;
 	bool visible_on_all_workspaces;
 	enum view_edge tiled;
 	uint32_t edges_visible;  /* enum wlr_edges bitset */
diff --git a/src/action.c b/src/action.c
index b564f4fd..bdbee257 100644
--- a/src/action.c
+++ b/src/action.c
@@ -1007,6 +1007,7 @@ actions_run(struct view *activator, struct server *server,
 			break;
 		case ACTION_TYPE_TOGGLE_TEARING:
 			if (view) {
+				view->tearing_override = !view->tearing_override;
 				switch (view->tearing_hint) {
 				case LAB_STATE_UNSPECIFIED:
 				case LAB_STATE_DISABLED:
diff --git a/src/tearing.c b/src/tearing.c
index 3cf1aa92..4b2470ed 100644
--- a/src/tearing.c
+++ b/src/tearing.c
@@ -14,7 +14,7 @@ set_tearing_hint(struct wl_listener *listener, void *data)
 {
 	struct tearing_controller *controller = wl_container_of(listener, controller, set_hint);
 	struct view *view = view_from_wlr_surface(controller->tearing_control->surface);
-	if (view) {
+	if (view && !view->tearing_override) {
 		/*
 		 * tearing_control->hint is actually an enum:
 		 * WP_TEARING_CONTROL_V1_PRESENTATION_HINT_VSYNC = 0
-- 
2.43.0
```

**Comment by Faugus** [comment]
@Ph42oN I just tested your changes and now I can't get `allowTearing` to work.
```
<core>
  <allowTearing>fullscreen</allowTearing>
</core>
...
<keybind key="C-F11">
  <action name="ToggleTearing" />
</keybind>
```
The game is jittery all the time. If I toggle it, it breaks the gamepad compatibility like before and the game is still jittery even running at high fps.

**Comment by Faugus** [comment]
[G-SYNC Pendulum Demo](https://us.download.nvidia.com/downloads/cool_stuff/demos/Setup_G-SYNC_1.13.exe) is another great tool to test VRR, Tearing, Vsync...
Just run it with Wine.

**Comment by Ph42oN** [comment]
> @Ph42oN I just tested your changes and it's behaving the same way it was.

Well my changes are to fix the problem that ToggleTearing does not override what application requests. That issue must be caused by something else.

Im not sure why you are having problem, it works as expected in games for me, at least on wine with xwayland. There was some talk about wine wayland previously... if its specific to that maybe i can test, but anyway wine wayland is unusable because camera does not turn at all with mouse on it (and this is not labwc specific, i tested on sway too).

**Comment by Consolatis** [comment]
I can't really see an issue in the logic of this PR and can't test it so if somebody else wants to take this over feel free.

Regarding the question of overriding what a client sets with the protocol: unless the client repeatedly sets it to disabled in an endless loop, the `ToggleTearing` action should overwrite whatever was set by a client (with only this PR applied) so I am not sure what is going on here.

**Comment by Ph42oN** [comment]
> Regarding the question of overriding what a client sets with the protocol: unless the client repeatedly sets it to disabled in an endless loop, the `ToggleTearing` action should overwrite whatever was set by a client (with only this PR applied) so I am not sure what is going on here.

That is what i would have expected too. But when making code to work with that expectation it doesn't work.

I believe tearing protocol was made to take info that clients were already giving on presentation, to not need to add tearing protocol support to every client. Maybe it just sets tearing hint based on that every frame.

**Comment by Consolatis** [comment]
Replaced by
- #1941

**Pull request closed without merging**
