### PR TITLE
Add Indonesia translation 

### PR DESCRIPTION
**Pull request by mantarimay**

### CODE REVIEW

**Comment by Consolatis** [comment]
Thanks for the translation.

CC @01micko 

Once approved I will squash the commits before merging.

**Comment by johanmalm** [comment]
Thanks.

**Comment by 01micko** [comment]
Apologies for tardy response but this and #877 LGTM without a thorough analysis.

**Comment by johanmalm** [comment]
> Apologies for tardy response but this and #877 LGTM without a thorough analysis.

I did a google translate on a few and just went for it :smile:

**Comment by johanmalm** [comment]
> Shouldn't it be `Indonesian` instead of `Indonesia` for `Language:`? Edit: Also the gettext example files use the short form id, es, de etc, does that matter?

Yes, ought to be `Indonesian`. 

I don't know much about PO files, but it looks like the first entry with an empty `msgid` string is considered as a header and that it contains meta-information about the content in the file. For the purposes of what we do, it doesn't seem like it makes a difference in practice, so I'm not overly bothered. Happy to merge if anyone fancies tidying up though.

Yes, looks like GNU guidance is `ll` notation (e.g. `id` and `de`). https://www.gnu.org/software/gettext/manual/html_node/Header-Entry.html

**Pull request merged**
