### PR TITLE
Store coordinate adjustments for touch points

### LINKED ISSUE #1033: Touch event coordinates jump when touch moves out of a window
To reproduce: in a program that accepts touch inputs, for scrolling for example, start scrolling with a touch. Carefully move the touch to the edge of the window and then beyond. Watch as the scroll position jumps significantly as the touch point exits the window edge.

I've reproduced this with both GTK3 programs and recent versions of the foot terminal emulator. A sample of `WAYLAND_DEBUG=client` output looks like this:

```
[3536863.998] wl_touch@25.frame()
[3536934.148] wl_touch@25.motion(965466162, 0, 518.50390625, 0.49609375)
[3536934.220] wl_touch@25.frame()
[3536973.622] wl_touch@25.motion(965466201, 0, 518.50390625, 0.87500000)
[3536973.667] wl_touch@25.frame()
[3537013.122] wl_touch@25.motion(965466241, 0, 518.50390625, 1.25390625)
[3537013.204] wl_touch@25.frame()
[3537072.918] wl_touch@25.motion(965466301, 0, 518.50390625, 1.63671875)
[3537072.987] wl_touch@25.frame()
[3537102.711] wl_touch@25.motion(965466331, 0, 518.12500000, 2.01562500)
[3537102.776] wl_touch@25.frame()
[3537739.068] wl_touch@25.motion(965466967, 0, 518.12500000, 1.63671875)
[3537739.118] wl_touch@25.frame()
[3537758.437] wl_touch@25.motion(965466986, 0, 518.12500000, 1.25390625)
[3537758.470] wl_touch@25.frame()
[3537768.118] wl_touch@25.motion(965466996, 0, 518.12500000, 0.87500000)
[3537768.138] wl_touch@25.frame()
[3537794.776] wl_touch@25.motion(965467016, 0, 518.12500000, 0.49609375)
[3537794.796] wl_touch@25.frame()
[3537808.099] wl_touch@25.motion(965467036, 0, 518.12500000, 0.11718750)
[3537808.133] wl_touch@25.frame()
[3537837.923] wl_touch@25.motion(965467066, 0, 1174.12500000, 101.73828125)
[3537837.981] wl_touch@25.frame()
[3537867.538] wl_touch@25.motion(965467095, 0, 1174.12500000, 101.35546875)
[3537867.593] wl_touch@25.frame()
[3537897.763] wl_touch@25.motion(965467125, 0, 1174.12500000, 100.97656250)
[3537897.816] wl_touch@25.frame()
[3537947.007] wl_touch@25.motion(965467175, 0, 1174.12500000, 100.59765625)
[3537947.064] wl_touch@25.frame()
[3538007.115] wl_touch@25.motion(965467235, 0, 1174.12500000, 100.21875000)
[3538007.183] wl_touch@25.frame()
[3538026.765] wl_touch@25.motion(965467255, 0, 1174.12500000, 99.83593750)
[3538026.832] wl_touch@25.frame()
[3538066.572] wl_touch@25.motion(965467294, 0, 1174.12500000, 99.45703125)
[3538066.635] wl_touch@25.frame()
[3538205.279] wl_touch@25.motion(965467433, 0, 1174.12500000, 99.07812500)
[3538205.325] wl_touch@25.frame()
[3538245.546] wl_touch@25.motion(965467473, 0, 1174.12500000, 98.69921875)
[3538245.612] wl_touch@25.frame()
```

I believe this happens because in `touch_motion` we call `touch_get_coords`, and `touch_get_coords` looks for the window beneath the touch to use as the origin of the touch event, but this window changes when the touch moves outside the window.

We should probably save the initial coordinates in layout or absolute space when a touch starts rather than adjusting them based on what's presently beneath the touch.

### PR DESCRIPTION
**Pull request by bi4k8**
Fixes #1033.

### CODE REVIEW

**Review by Consolatis — COMMENTED** [review]
I currently can not really test it but I assume you did so already.
Looks good on the first glance, just 2 minor comments below.

We could also consider moving `struct touch_point` and the list to `src/touch.c` as `static wl_list touch_points`. As we already have a `_init()` function in there the `wl_list_init()` call shouldn't be an issue either and we'd prevent blowing up `labwc.h` and `struct seat` even more.

**Comment by bi4k8** [comment]
Both comments addressed. As for moving the `touch_point` list from the seat to a global, I don't think we really plan to support multi-seat, but conceptually the touch points *are* associated with the seat rather than being standalone. I don't know whether (in theory) touch IDs are scoped to seats or globally unique (ignoring reuse for later touches), but I feel better scoping them to the seat even though we only have one.

If you feel strongly we can move the touch points list out of the seat; it's not a functional concern at this point.

**Comment by Consolatis** [comment]
> If you feel strongly we can move the touch points list out of the seat; it's not a functional concern at this point.

No, I agree with your argumentation, they conceptually belong to the seat so lets keep them there.
I'd say lets move `struct touch_point` to `touch.c` but keep the list itself in `struct seat`.

I'd prefer if we can get `labwc.h` to be less of an lets-put-everything-in-there bucket over time, so struct definitions that are only used in a specific file should be private for that file instead.

**Comment by bi4k8** [comment]
Done.

**Comment by bi4k8** [comment]
CI on Debian and Void-musl failed to git clone wlroots...

**Comment by Consolatis** [comment]
Sweet, thanks for working on this.

As said earlier, I can't really test it currently but I trust that you have tested it so I am going for the merge.

**Pull request merged**
