### PR TITLE
Resolve focus change theme color transition error

### PR DESCRIPTION
**Pull request by yuanye100**
When using the server decoration, the focus shifts to the client decorated with the client, and the theme color will not become inactive.

### CODE REVIEW

**Comment by Consolatis** [comment]
This doesn't seem to switch the previous active view (`view->server->ssd_focused_view`) back to inactivate state.

The issue this is trying to solve is when switching between CSD (client side decoration) and SSD (server side decoration) window?

**Comment by johanmalm** [comment]
@yuanye100 
Appreciate the contribution :smile:
The code looks good, but I'd appreciate help understanding the issue.
Could you describe what steps you take to change focus without the server-side-deco color changing.

**Comment by yuanye100** [comment]
Open a CSD client and an SSD client. When the focus is on the SSD client, the decoration color is active. However, when the focus is transferred to the CSD client, the decoration color of the SSD client is not changed to inactive. To solve this problem, I will change the flag recording the SSD status, and directly judge the status of the setting client, instead of judging the SSD client alone.

**Comment by johanmalm** [comment]
@yuanye100 Sorry we've been slow to respond properly to this.
I get the issue now. I think #504 covers it. It's a similar solution to what you've provided, but does some additional re-factoring.

**Comment by johanmalm** [comment]
Assume this is now overtaken by events (#504)?

**Pull request closed without merging**
