### PR TITLE
CONTRIBUTING.md: correct the instructions for adding a locale code

### PR DESCRIPTION
**Pull request by 01micko**
The wording was wrong. Should be in alphabetical order.

### CODE REVIEW

**Comment by Consolatis** [comment]
Thanks as usual :)

**Comment by stefonarch** [comment]
Didn't notice this, here could be a hint for weblate too. I changed settings so new users should be able now to create language files.

**Comment by 01micko** [comment]
I was thinking about this but why don't you add it? You know all the links
and stuff.

**Comment by stefonarch** [comment]
Because I noticed this page only now ;)

**Comment by 01micko** [comment]
Well, now that you know :)

**Pull request merged**
