### PR TITLE
[wip] src/xdg.c: prevent configure requests before map

### PR DESCRIPTION
**Pull request by Consolatis**
Fixes:
- #1994

### CODE REVIEW

**Comment by Consolatis** [comment]
@jlindgren90 any objections to this PR?

Obviously the logging will be removed.

**Comment by jlindgren90** [comment]
Haven't had time to test. Does e.g. `foot --maximized` still work with this?

**Comment by jlindgren90** [comment]
I'd also be curious if/how this interacts with #1956. I may find time to check later, don't hold things up waiting for me though.

**Comment by Consolatis** [comment]
> Haven't had time to test. Does e.g. `foot --maximized` still work with this?

Yes, it ignores the first maximize request (before mapping) but it is then maximized within the map handler.

I can't reliably test timings and glitches like repositioning currently as my Debian install is too old for compiling the DRM backend and (gles2 renderer) for wlroots 0.18 thus I have to test with pixman and nested only. I didn't verify the startup flow for `foot -m` via `WAYLAND_DEBUG` either.

**Comment by tokyo4j** [comment]
I believe this PR is doing right.

But as I said in https://github.com/labwc/labwc/issues/1994#issuecomment-2235765192, the bug is due to [wlroots change which changes the timing of `new_surface` event](https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/e8413660686bf94322799470ef5b109ea4580cc9) and [similar change for layer shell](https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/e8413660686bf94322799470ef5b109ea4580cc9) follows it. So we should make similar fix also for layer shell (not sure it should be done in this PR).

**Comment by droc12345** [comment]
tokyo4j, patch works for me and gets rid of layer-shell message.

No opinion on whether to add to this PR or a new one.

**Comment by Consolatis** [comment]
I can add the layerchange to this PR but #1956 might fix the issue as well. Didn't yet have time to look into that PR in detail.

**Comment by jlindgren90** [comment]
I think this is correct but only half the fix. More complete fix in #2007.

I didn't look into the similar layer-shell warning.

**Comment by Consolatis** [comment]
> I didn't look into the similar layer-shell warning.

I am actually not sure if that whole block should be removed. If the surface isn't mapped it doesn't make sense to arrange it either.
It seems this was introduced waaay back in 2020 via the initial layershell implementation a4c22f7c4de1319e1e252d4a1d65d033fcb93ef2.

**Comment by tokyo4j** [comment]
> I am actually not sure if that whole block should be removed. If the surface isn't mapped it doesn't make sense to arrange it. And the surface should not be mapped in the new_surface handler either.
> 
> It seems this was introduced waaay back in 2020 via the initial layershell implementation https://github.com/labwc/labwc/commit/a4c22f7c4de1319e1e252d4a1d65d033fcb93ef2.

Agreed.

**Pull request closed without merging**
