### PR TITLE
keybinds: allow non-english based keybinds

### PR DESCRIPTION
**Pull request by Consolatis**
Split from
- #1072

### CODE REVIEW

**Comment by johanmalm** [comment]
LGTM

Is it worth adding a comment to describe why we convert to Unicode and back?

**Comment by Consolatis** [comment]
> Is it worth adding a comment to describe why we convert to Unicode and back?

Added a comment explaining why we try the additional utf8 -> unicode -> keysym translation.

**Comment by ringo32** [comment]
sway does bindcode 10 as example like i3wm, hyprland 0x10  from wev? is for me &  , shift & is 1 , azerty, also got " in between.., what i want to ask is there a doc or example how to use keycodes ?

**Comment by johanmalm** [comment]
> sway does bindcode 10 as example like i3wm, hyprland 0x10 from wev? is for me & , shift & is 1 , azerty, also got " in between.., what i want to ask is there a doc or example how to use keycodes ?

- https://labwc.github.io/faq.html#common-keybinds
- Step 3 of https://labwc.github.io/getting-started.html

```
<keybind key="W-1"><action name="GoToDesktop" to="1"/></keybind>
<keybind key="W-2"><action name="GoToDesktop" to="2"/></keybind>
<keybind key="W-3"><action name="GoToDesktop" to="3"/></keybind>
```

**Comment by ringo32** [comment]
> > sway does bindcode 10 as example like i3wm, hyprland 0x10 from wev? is for me & , shift & is 1 , azerty, also got " in between.., what i want to ask is there a doc or example how to use keycodes ?
> 
>     * https://labwc.github.io/faq.html#common-keybinds
> 
>     * Step 3 of https://labwc.github.io/getting-started.html
> 
> 
> ```
> <keybind key="W-1"><action name="GoToDesktop" to="1"/></keybind>
> <keybind key="W-2"><action name="GoToDesktop" to="2"/></keybind>
> <keybind key="W-3"><action name="GoToDesktop" to="3"/></keybind>
> ```

that doesnt work on a azerty keyboard ?

**Comment by johanmalm** [comment]
> that doesnt work on a azerty keyboard ?

Would you mind opening a new issue for this with some more details. I'm not familiar with azerty + bincodes so the more context you can provide the easier it is to help.

**Comment by aveltras** [comment]
I had the same issue.
Turns out on azerty you can use **W-ampersand** instead of **W-1** or **W-&** to bind **Super+1** key for example.
Keys can be identified using **wev**.

For example:

```
<keybind key="W-ampersand">
  <action name="Execute" command="wlrctl window focus firefox || firefox" />
</keybind>
```

**Comment by ringo32** [comment]
> I had the same issue.
> Turns out on azerty you can use **W-ampersand** instead of **W-1** or **W-&** to bind **Super+1** key for example.
> Keys can be identified using **wev**.
> 
> For example:
> 
> ```
> <keybind key="W-ampersand">
>   <action name="Execute" command="wlrctl window focus firefox || firefox" />
> </keybind>
> ```

Ok interesting, personal I like the way sway or hyprcrl do
Sway bindcode 10 for 1  or hyprland keycode 0x10..all is back to find in wev..ampersand is kinda big..but it is what is wil try to adapt it.

**Comment by Consolatis** [comment]
`W-0x10` should work as well (if `0x10` is what wev reports).

**Comment by ringo32** [comment]
Thank you for feedback

**Pull request merged**
