### PR TITLE
xwayland: assign view->surface earlier in map handler

### PR DESCRIPTION
**Pull request by johanmalm**
...as it needs to be set before honouring xwayland_surface->fullscreen because that calls desktop_update_top_layer_visiblity() which relies on view->surface being set in view_is_focusable() since 13d0b14.

Fix bug introduced by PR #1237 which fails to hide the xfce4-panel (or any other layer-shell client in the top layer) whilst gaming in fullscreen. The bug can be observed with the following games:

- Alan Wake 2 (wine)
- Starfield (steam+proton)
- Cyberpunk (steam+proton)
- Quake 1 Remaster (steam-native)

Fixes: #661 (the last bit of it)

Reported-by: @ScarecrowDM
Helped-by: @Consolatis

### CODE REVIEW

**Comment by johanmalm** [comment]
@ScarecrowDM any chance you could test with this patch?

**Comment by Consolatis** [comment]
Could reproduce the issue by using a panel in top layer mode + `GDK_BACKEND=x11 mate-terminal --full-screen`.
This patch hides the panel correctly for me when mate terminal starts up.

There is another issue in that using `A-Space` to minimize a fullscreen window does not trigger the top layer update routine but I think that is a minor issue and can be until after the release.

**Comment by ScarecrowDM** [comment]
Just gave it a try and indeed the panel is hiding correctly now.
Thank you! :tada:

**Comment by johanmalm** [comment]
> Just gave it a try and indeed the panel is hiding correctly now. Thank you! 🎉

Beautiful. Thank you both

**Pull request merged**
