### PR TITLE
nls: updates for new strings in menus

### PR DESCRIPTION
**Pull request by 01micko**
- also fixes updating tr.po file
- more descriptive instructions in CONTRIBUTING.md
- fix comments in po/pot files when using meson gettext tools

### CODE REVIEW

**Comment by 01micko** [comment]
@johanmalm do you mind updating `po/sv.po`?

Same @ersen0 for `po/tr.po`

TIA

**Comment by ersen0** [comment]
>**Move left**
>Sola git

>**Move right**
>Sağa git

>**Workspace**
>Çalışma alanı

@01micko can you update po file with the above?

**Comment by johanmalm** [comment]
LGTM
Swedish translation updated as requested :smile:

**Comment by johanmalm** [comment]
Changed to draft to avoid me or @Consolatis merging before @01micko is happy.

**Comment by 01micko** [comment]
@01micko can you update po file with the above?

@ersen0 no problem :smile:

**Comment by 01micko** [comment]
This is now ready unless you want me to squash it down and force-push.
@Consolatis @johanmalm

**Comment by 01micko** [comment]
Thanks @johanmalm :smile:

**Comment by johanmalm** [comment]
Thank you too!

**Pull request merged**
