### PR TITLE
keyboard: broadcast modifiers

### PR DESCRIPTION
**Pull request by johanmalm**
...to all clients rather than just the one with keyboard focus on keyboard enter/create, modifer press/release and wlr_seat_set_keyboard().

This enables:

- Clients such as panels to display the current keyboard layout without introducing new wayland protocols or other IPC.

- Unfocused xdg-shell clients to understand button press with keyboard modifiers for example Ctrl+click.

The keymap is forwarded to all clients in wlr_seat_set_keyboard(). When a keymap contains multiple layouts, the selection is made via modifiers, which previously were only sent to the client with keyboard focus.

Tested with: https://github.com/johanmalm/keyboard-layout

Ref: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4496

Fixes: #2271

### CODE REVIEW

**Comment by jlindgren90** [comment]
Yep, this works for me. Thanks!

**Comment by johanmalm** [comment]
v2: Added a longer comment and changed the function name.

Ready for review from my perspective.

If we find that this has side-effects, I suggest we make it optional before the next release.

If we do make it optional, we ought to consider pass the modifiers to the client with pointer-focus even if `broadcastModifiersToUnfocusedClients == false`

**Comment by jlindgren90** [comment]
LGTM

**Comment by Consolatis** [comment]
LGTM as well, timing of the PR is also nice as we are at the start of a release cycle and thus have plenty time for user feedback in case this breaks some clients.

**Comment by johanmalm** [comment]
> Ohh I thought this was going to fix #1507. Any news on that? :)

If you've got the setup, any chance of trying?

**Pull request merged**
