### PR TITLE
Option to show full app_id in window switcher

### LINKED ISSUE #1073: Different app_id in OSD and windowRule
When using Alt-Tab to display OSD (windowSwitcher), I can see that that Telegram app_id is `desktop`.

However, when trying to match this app_id using `identifier` in `windowRule`, the match doesn't happen.

I used waybar to figure out the Telegram app_id, which is apparently `org.telegram.desktop`.

So this now works (matches):

```
    <windowRule identifier="org.telegram.desktop" serverDecoration="no">
      <action name="SnapToEdge" direction="right"/>
    </windowRule>
```

It seems like OSD and windowRule use different approaches to getting `app_id/identifier`.

Can they be consistent with each other?

What is the proper way to get `app_id` in labwc anyway in order to create window rules?

### PR DESCRIPTION
**Pull request by kyak**
It is now possible to specify whether to show full application identifier or the trimmed variant in window switcher OSD.

Closes #1073

### CODE REVIEW

**Comment by Consolatis** [comment]
LGTM, up to @johanmalm if we want to keep the new `full_app_id` option or if we should instead turn this into a new `<field content="full_app_id">` that could be used instead of `identifier`.

Technically, we should actually use this as `identifier` and add a new `content` type like `trimmed_app_id` or something. We could then change the default to use the new `trimmed_app_id` field which would then be backwards compatible to all existing configs that do \*not\* define the fields. It would however break for configs that currently define the `identifier` field.

**Comment by johanmalm** [comment]
> Technically, we should actually use this as `identifier` and add a new `content` type like `trimmed_app_id` or something. We could then change the default to use the new `trimmed_app_id` field which would then be backwards compatible to all existing configs that do *not* define the fields. It would however break for configs that currently define the `identifier` field.

I think we should go for correctness and consistency with the wider code-base, and take the regression hit.

So, “identifier” should mean app-id/wm-class (foo.bar.baz). Suggest we add “trimmed_identifier” and make that default. I’m keen not to use app_id as it’s Wayland specific.

**Comment by kyak** [comment]
@Consolatis @johanmalm I've updated the PR with your suggested approach. I've kept the history, but feel free to squash when merging.

**Comment by johanmalm** [comment]
LGTM

**Comment by johanmalm** [comment]
Thanks!

**Comment by charbelnicolas** [comment]
I changed identifier to trimmed_identifier and saw no difference, whats the catch?

**Comment by Consolatis** [comment]
> I changed identifier to trimmed_identifier and saw no difference, whats the catch?

It only matters for things like `org.mozilla.firefox` which should be `firefox` in the trimmed version and the full string in the non-trimmed version.

**Pull request merged**
