### PR TITLE
Fix HiDPI scaling.

### LINKED ISSUE #105: Menus, titlebar text, and rounded corners are blurred when output scale is >1
For some reason labwc does not scale the output on my laptop. I have 3000x2000 14" display and I see the following:

labwc: 
scaling-bad

sway:
scaling-good

### PR DESCRIPTION
**Pull request by ARDiDo**
Once it's done, this should close #105.
- [X] Scale views that originate on the HiDPI monitor
- [X] Scale views originating from non-HiDPI monitors
~~Scale menu and titlebar text~~

### CODE REVIEW

**Comment by johanmalm** [comment]
Should the surface_*_for_each_surface() functions be static void?
Otherwise looks good

**Comment by johanmalm** [comment]
Clang build fails because of an old “unused variables” in layers.c popup_damage()
I’ve left that a bit untidy because I think damage tracking will be taken care of by wlr_scene when we move to that.
Do you want me to sort out, or do you want to do it yourself? Suggest we just go with damage-all-outputs for now.

**Comment by ARDiDo** [comment]
Yeah, the iterators should be static void. That was leftover from before the view_output_*() functions were made. I'll fix it in the next commit.
I'll leave fixing the build failures to you, since you know more about the situation than I do.

**Comment by johanmalm** [comment]
clang-warning fixed.

**Comment by heroin-moose** [comment]
Fixes alacritty for me. However, it seems that the logical screen size is now 4 times bigger than the physical one, because maximized applications are only partially visible.

**Comment by heroin-moose** [comment]
Btw, labwc's menus still looks blurry.

**Comment by ARDiDo** [comment]
Thanks for the feedback @heroin-moose. The latest commit fixed the scaling and placement on my end, and I would be very grateful if you could test it on your machine.
Being honest, I think I should just merge the commits I have, and open another pull request once I'm done scaling the menu and titlebar text. Fixing that involves working with pango and cairo, and I'm not familiar with those at all. I don't want to fix any merge conflicts that will eventually arise, and I want to be able to take my time on it.

**Comment by johanmalm** [comment]
@ARDiDo sounds a good plan.

With the menu/etc, do you think the approach is to just make textures bigger at source by a factor of scale? And then remove line https://github.com/labwc/labwc/blob/aa9720f6273de9117694064479251d7961af7816/src/output.c#L506

Guess it might get more complicated if different outputs gave different scales.

**Comment by heroin-moose** [comment]
OSD yes, maximize yes, however snaptoedge still moves window beyond the screen.

**Comment by ARDiDo** [comment]
That should about do it. Thanks for the help @heroin-moose, and thank you for the advice @johanmalm.

**Pull request merged**
