### PR TITLE
common/font: avoid rendering semi-transparent background twice

### PR DESCRIPTION
**Pull request by jlindgren90**
Fixes: (the rest of) #1684

### CODE REVIEW

**Comment by jlindgren90** [comment]
CodeStyleCheck is complaining about `PangoContext` being camel-case. Not sure what to do about that...

**Comment by johanmalm** [comment]
LGTM.

Great effort. Also, really nice work on the vulkan renderer fix (wlroots MR4635).

Consider describing the subpixel logic (no subpixel when alpha != 1.0) and why in the commit message for future devs.

Patch to get rid of the coding-style warning:

```
diff --git a/scripts/checkpatch.pl b/scripts/checkpatch.pl
index 14fdb88..17749eb 100755
--- a/scripts/checkpatch.pl
+++ b/scripts/checkpatch.pl
@@ -5658,6 +5658,7 @@ sub process {
 			    $var !~ /^(?:PangoLayout|PangoFontDescription)/ &&
 			    $var !~ /^(?:PangoTabArray|PangoRectangle)/ &&
 			    $var !~ /^(?:PangoWeight|_PangoFontDescription)/ &&
+			    $var !~ /^(?:PangoContext)/ &&
 			    $var !~ /^(?:xmlNode|xmlIsBlankNode|xmlAttr)/ &&
 			    $var !~ /^(?:xmlGetProp|xmlChar|xmlDoc)/ &&
 			    $var !~ /^(?:xmlReadFile|xmlDocGetRootElement)/ &&
```

**Comment by Consolatis** [comment]
> LGTM.
> 
> Great effort. Also, really nice work on the vulkan renderer fix (wlroots MR4635).
> 
> Consider describing the subpixel logic (no subpixel when alpha != 1.0) and why in the commit message for future devs.
> 
> Patch to get rid of the coding-style warning:
> 
> ```
> diff --git a/scripts/checkpatch.pl b/scripts/checkpatch.pl
> index 14fdb88..17749eb 100755
> --- a/scripts/checkpatch.pl
> +++ b/scripts/checkpatch.pl
> @@ -5658,6 +5658,7 @@ sub process {
>  			    $var !~ /^(?:PangoLayout|PangoFontDescription)/ &&
>  			    $var !~ /^(?:PangoTabArray|PangoRectangle)/ &&
>  			    $var !~ /^(?:PangoWeight|_PangoFontDescription)/ &&
> +			    $var !~ /^(?:PangoContext)/ &&
>  			    $var !~ /^(?:xmlNode|xmlIsBlankNode|xmlAttr)/ &&
>  			    $var !~ /^(?:xmlGetProp|xmlChar|xmlDoc)/ &&
>  			    $var !~ /^(?:xmlReadFile|xmlDocGetRootElement)/ &&
> ```

Should we just use something like `/^(?:Pango\w+)/` ?
Also I couldn't find any `_PangoFontDescription` in the labwc codebase, might be outded.

**Review by ahesford — COMMENTED** [review]
Not sure if rounding errors might affect the calculation of the alpha fraction. Maybe something like

    0xFF * bg_color[3] > 0xFE
    0xFF * bg_color[3] <= 0xFE

are better to avoid rounding issues, and provide the precision necessary for percent as well as hex specification of alpha channel.

**Comment by jlindgren90** [comment]
> Consider describing the subpixel logic (no subpixel when alpha != 1.0) and why in the commit message for future devs.

Sure, maybe just copy the block comment from the code into the commit message?

**Comment by jlindgren90** [comment]
> Not sure if rounding errors might affect the calculation of the alpha fraction.

It didn't seem to occur in practice. 255/255 and 100/100 should both come to exactly 1.0f. I could be missing something here though.

**Comment by jlindgren90** [comment]
v2: use 0.999 alpha cutoff, fix CodeStyleCheck, expand commit message

**Comment by Consolatis** [comment]
LGTM, not tested.
Feel free to rebase and merge if you are satisfied with the PR.

**Pull request merged**
