### PR TITLE
add menu border option

### PR DESCRIPTION
**Pull request by davidphilipbarr**
Adds an option for a menu border with menu.border.width and menu.border.color 

not entirely sure this is the best method? I'm also not sure if default should be off, will need some tidying if it looks functionally ok?

#2148 

menb

### CODE REVIEW

**Comment by tokyo4j** [comment]
Please fix the style errors from `scripts/checkpatch.pl` and remove the redundant `theme.c`.

**Comment by tokyo4j** [comment]
I opened #2241 that adds `outline_rect`, a rectangular outline that consist of 4 scene_rects. Your solution (drawing a border as difference of two scene_rects) will work, but I think using the new `outline_rect` will make the codebase more consistent as we already have `multi_rect` (a rectangle that consists of nested 3 rectangular outlines with different colors).  

As for this PR, please fix errors from CI and remove the redundant `theme.c`. The check by CI can be locally executed with `scripts/check`.

**Comment by davidphilipbarr** [comment]
Thanks for looking at this, i figured it might not be the *best* way to do it, i'll tidy up as per your advice but feel free to ignore if you have alternative plans, i'm just getting familiar with the code base so my changes are quite basic.  

...how embarrassing leaving that themerc in there :)

**Comment by johanmalm** [comment]
Just thinking ahead - we ought to consider the possibility of padding + rounded corners in future.
Therefore, would it make sense to just generate a background surface and include the border in that?

Ref:
- https://github.com/labwc/labwc/blob/da68df5f5b6b1c7e8729bdfcd1e527e83f547067/src/osd.c#L210-L223
- https://github.com/labwc/labwc/blob/da68df5f5b6b1c7e8729bdfcd1e527e83f547067/src/common/graphic-helpers.c#L81

**Comment by davidphilipbarr** [comment]
I've fixed the CI errors and the separator placement now.

**Comment by tokyo4j** [comment]
> Just thinking ahead - we ought to consider the possibility of padding + rounded corners in future.
Therefore, would it make sense to just generate a background surface and include the border in that?

I think we should stick to scene-rect-based approach in this PR because the widths of menu items are dynamically updated after parsing `menu.xml` or when opening `client-list-combined-menu`/`client-send-to-menu`  in the current implementation.

**Comment by tokyo4j** [comment]
> I think we should stick to scene-rect-based approach in this PR because the widths of menu items are dynamically updated after parsing menu.xml or when opening client-list-combined-menu/client-send-to-menu in the current implementation.

I worked around this problem and implemented a prototype of background + rounded corner + padding support for menus.

https://github.com/labwc/labwc/compare/master...tokyo4j:labwc:rounded-menu

20241018_21h36m20s_grim

If we decide to proceed on this approach, I'll open a PR later.

@davidphilipbarr Sorry if we decide to take this PR over. I really appreciate your contribution that showed a solution for menu borders and moved our discussion forward.

**Comment by davidphilipbarr** [comment]
I much prefer your solution! Happy if i just helped in any way to move things along!

**Comment by johanmalm** [comment]
> I worked around this problem and implemented a prototype of background + rounded corner + padding support for menus.
> 
> [master...tokyo4j:labwc:rounded-menu](https://github.com/labwc/labwc/compare/master...tokyo4j:labwc:rounded-menu)
> 
> If we decide to proceed on this approach, I'll open a PR later.

This patch looks very promising and I think it's the right direction. Suggest we proceed with this approach.

**Comment by TheESN** [comment]
How is this PR going?

**Comment by tokyo4j** [comment]
> How is this PR going?

We've finish some refactoring as preparations for borders + rounded corners + padding around items, so I'll open another PR soon.

**Pull request closed without merging**
