### PR TITLE
Avoid setting `view->w` and `view->h` before xdg view commit

### PR DESCRIPTION
**Pull request by bi4k8**
A cleaner fix for the second half of #647. Supersedes #676.

### CODE REVIEW

**Comment by jlindgren90** [comment]
Thanks! Looks reasonable to me. I wonder if adding some kind of a comment to the code would be good so we don't inadvertantly introduce a similar bug again in future?

**Comment by Consolatis** [comment]
Looked a bit more into this and had a quick test nested: everything seems fine (only tested with `foot -m` / `foot -F` though).
Applications starting maximized or fullscreen (and thus may not have the original geometry set) are dealt with by setting the hardcoded fallback geometry:
https://github.com/labwc/labwc/blob/3dec9cf40cebe0e231e42722caa3c8fbdc2d5f83/src/view.c#L323-L340

> I wonder if adding some kind of a comment to the code would be good so we don't inadvertently introduce a similar bug again in future?

Agree, a comment to explain why we don't set them manually on map would be appreciated, (e.g. just a copy the first part of the commit message should be enough).

**Comment by bi4k8** [comment]
Comment added.

**Comment by Consolatis** [comment]
Merging. Thanks again for the extensive investigation and the two fixes regarding OSD and newly mapped windows.

**Pull request merged**
