### PR TITLE
xdg: handle `show_window_menu` requests

### PR DESCRIPTION
**Pull request by tokyo4j**
Screenshot with gedit:

20240921_19h53m54s_grim

### CODE REVIEW

**Comment by johanmalm** [comment]
Wow. Very nice. I didn't even realize there was such a request.

**Comment by jp7677** [comment]
Hi @tokyo4j I think this is not yet complete. I'm seeing that the client window nicely opens on right-click in e.g. Gnome-Calendar (GTK4, CSD), but when executing an action in the menu, the action will be executed for another window or not at all or labwc crashes.  

Consider the following scenario:

- Open Gnome-Calendar (CSD) and  Gnome-Terminal (SSD) next to each other 
- Open the window menu in Gnome-Calendar by right click in the CSD title bar and select maximize.
- What happens is that Gnome-Terminal will be maximized instead and not Gnome-Calendar

With just firefox (CSD) and Gnome-Calendar open, I managed to hit an assert in labwc by executing a window action in the menu spawned from  Gnome-Calendar. The back trace looks like this:

```gdb
#0  0x00007f8b11ca8664 in __pthread_kill_implementation () at /lib64/libc.so.6
#1  0x00007f8b11c4fc4e in raise () at /lib64/libc.so.6
#2  0x00007f8b11c37902 in abort () at /lib64/libc.so.6
#3  0x00007f8b11c3781e in __assert_fail_base.cold () at /lib64/libc.so.6
#4  0x00007f8b11c47d87 in __assert_fail () at /lib64/libc.so.6
#5  0x0000000000429f4c in xdg_surface_from_view (view=<optimized out>) at ../src/xdg.c:31
#6  xdg_toplevel_from_view (view=<optimized out>) at ../src/xdg.c:41
#7  xdg_toplevel_view_maximize (view=<optimized out>, maximized=<optimized out>) at ../src/xdg.c:479
#8  0x00000000004265f1 in set_maximized (view=0x3ec14630, maximized=VIEW_AXIS_BOTH) at ../src/view.c:1225
#9  view_maximize (view=0x3ec14630, axis=VIEW_AXIS_BOTH, store_natural_geometry=<optimized out>) at ../src/view.c:1351
#10 view_maximize (view=0x3ec14630, axis=VIEW_AXIS_BOTH, store_natural_geometry=<optimized out>) at ../src/view.c:1312
#11 0x00000000004101c0 in actions_run (activator=<optimized out>, server=0x7ffddf4e4f70, actions=0x3ea3f8d0, cursor_ctx=<optimized out>) at ../src/action.c:957
#12 0x000000000043f960 in menu_execute_item (item=0x3ea3f8d0) at ../src/menu/menu.c:1596
#13 0x00000000004418dd in menu_execute_item (item=<optimized out>) at ../src/menu/menu.c:1568
#14 menu_call_selected_actions (server=<optimized out>) at ../src/menu/menu.c:1626
#15 0x000000000043a105 in cursor_process_button_release (seat=seat@entry=0x7ffddf4e50c0, button=button@entry=272, time_msec=time_msec@entry=2945508)
    at ../src/input/cursor.c:1092
#16 0x000000000043a48e in cursor_emulate_button (seat=0x7ffddf4e50c0, button=272, state=WL_POINTER_BUTTON_STATE_RELEASED, time_msec=2945508)
    at ../src/input/cursor.c:1244
#17 0x00007f8b12ba906c in wl_signal_emit_mutable () at /lib64/libwayland-server.so.0
#18 0x00007f8b12ba906c in wl_signal_emit_mutable () at /lib64/libwayland-server.so.0
#19 0x00007f8b12adec05 in handle_libinput_readable () at /lib64/libwlroots-0.18.so
#20 0x00007f8b12baac92 in wl_event_loop_dispatch () at /lib64/libwayland-server.so.0
#21 0x00007f8b12baccf5 in wl_display_run () at /lib64/libwayland-server.so.0
#22 0x000000000040e89f in main (argc=<optimized out>, argv=<optimized out>) at ../src/main.c:220
```

So looks like the window menu is somehow liked to the wrong view.

PS: Please let me know if you want me to open a new issue for better traceability instead of reporting here.

**Comment by tokyo4j** [comment]
Oh I see. I'll fix it soon. Thank you for reporting!

**Comment by tokyo4j** [comment]
Opened a PR. I don't know why I made such a stupid mistake...

**Pull request merged**
