### PR TITLE
Add lsan.supp

### PR DESCRIPTION
**Pull request by johanmalm**
...so suppress errors from ASAN with EGL renderer.

Also add Makefile to simplify running with sanitizer and this suppression file.

Related-to: #2331

### CODE REVIEW

**Comment by Consolatis** [comment]
The `Makefile` in the root directory feels weird IMHO. It could make users expect to run `make` rather than `meson setup build; [..]`.

This feels more like it would belong in some test, scripts or ci directory.

**Comment by tokyo4j** [comment]
Strangely, I can no longer see memory leak errors from ASAN (which were locally present in 2 weeks ago) in the current master. Were you able to see the errors and confirm this PR suppresses them?

**Comment by johanmalm** [comment]
> Strangely, I can no longer see memory leak errors from ASAN (which were locally present in 2 weeks ago) in the current master. Were you able to see the errors and confirm this PR suppresses them?

Yes, I saw the EGL memory leaks, and the lsan.supp file suppresses them.

**Comment by johanmalm** [comment]
> The `Makefile` in the root directory feels weird IMHO. It could make users expect to run `make` rather than `meson setup build; [..]`.
> 
> This feels more like it would belong in some test, scripts or ci directory.

Yes, I did ponder that. It's nice to keep the toplevel directory clean actually isn't it. I'll do a v2.

**Comment by johanmalm** [comment]
Okay, ready for review.

**Comment by tokyo4j** [comment]
> > Strangely, I can no longer see memory leak errors from ASAN (which were locally present in 2 weeks ago) in the current master. Were you able to see the errors and confirm this PR suppresses them?
> 
> Yes, I saw the EGL memory leaks, and the lsan.supp file suppresses them.

I can see the error messages again after downgrading mesa from 1:24.2.7-1 to 1:24.2.5-1... that's strange.

**Comment by Consolatis** [comment]
I've added a runtime leak test to the CI in #2383.

That one uses `LSAN_OPTIONS=suppressions=scripts/asan_leak_supressions` (which only contains `libfontconfig.so` because the version shipped by Debian Testing seems to leak).

**Comment by Consolatis** [comment]
> Well, shall we delete this PR. Probably not needed.

Up to you, I don't see anything wrong with adding `libEGL_mesa.so` to `scripts/asan_leak_suppression` and have a small wrapper to compile and start labwc with the leak detection enabled.

**Comment by johanmalm** [comment]
Like so…?

**Comment by Consolatis** [comment]
Yep, LGTM

**Pull request merged**
