### PR TITLE
NLS: translate "Workspaces" in rcxml.c. closes #1630

### LINKED ISSUE #1630: NLS: "Workspace"
At the time of writing, `rcxml.c` at line ~1484~ contains the string "Workspace". 

Being an UI element it probably should be internationalised.

Whoops line 1384

### PR DESCRIPTION
**Pull request by 01micko**
Translators - no need to update as "Workspaces" is already covered in `menu.c` and gettext is smart enough to re-use it.

I took the liberty to update all the comments in the `po` files too. tested about 6 locales and all works, including RTL in Arabic (https://github.com/labwc/labwc/issues/1630#issuecomment-2002306206). Would appreciate some CJK testing as I don't have those fonts, but there should be no problem.

### CODE REVIEW

**Comment by Consolatis** [comment]
If you remove the 2 additional spaces I am ready to merge.
I can squash the commit directly within the PR so just pushing a fixup commit is totally fine.

**Comment by 01micko** [comment]
Oh, both eh?

Lol, just removed end one, will do other now.

**Comment by Consolatis** [comment]
Thanks as always :)

**Comment by 01micko** [comment]
> Would appreciate some CJK testing as I don't have those fonts, but there should be no problem.

As a follow up to this @Consolatis , @johanmalm I installed `wqy-microhei.ttc` CJK font and added this to my `rc.xml`

```xml
    <font>
      <name>WenQuanYi Micro Hei</name>
      <size>10</size>
      <slant>normal</slant>
      <weight>normal</weight>
    </font>
```

_osd_ and _workplaces_ work correctly as far as I can tell just by comparing the strings to the respective `zh_CN.po` and `ja.po` for Chinese and Japanese.

**Pull request merged**
