### PR TITLE
src/view.c: guard xwayland include

### PR DESCRIPTION
**Pull request by Consolatis**
Fixes:
- #1118

### CODE REVIEW

**Comment by jlindgren90** [comment]
Yep, my fault, sorry about that. LGTM.

**Comment by Consolatis** [comment]
Well, malm and me didn't see it either :)

**Comment by jlindgren90** [comment]
Maybe we could add a CI build variant that builds wlroots without X11 support...

**Comment by Consolatis** [comment]
Yep, my thought as well:
- #1121

**Pull request merged**
