### PR TITLE
config: Fix RaiseOnFocus always setting FollowMouse

### PR DESCRIPTION
**Pull request by misyltoad**
Signed-off-by: Joshua Ashton <joshua@froggi.es>

### CODE REVIEW

**Comment by Consolatis** [comment]
What was the reasoning behind this change? It would be quite handy to have that option while disabling FollowMouse.

**Comment by johanmalm** [comment]
Guess it was to try to increase consistency with openbox, where raiseOnFocus only applies if followMouse is set.

http://openbox.org/wiki/Help:Configuration

Happy to simplify this to set them independently of each other.

@Joshua-Ashton shout if you have an issue with this.

**Comment by Joshua-Ashton** [comment]
I made this change because originally because even if the option was set to false, it would enable follow mouse if it existed -- and I didn't want that.

**Comment by Consolatis** [comment]
@Joshua-Ashton I completely missed the removed line (which was the whole reason for this PR) and only saw you enabled FollowMouse once RaiseOnFocus was true. Sorry :)

> consistency with openbox, where raiseOnFocus only applies if followMouse is set.  

Well it enables followMouse when raiseOnFocus is set. So its actually the other way round.

**Comment by johanmalm** [comment]
I've de-couple them. c797dbe1

**Comment by johanmalm** [comment]
> So its actually the other way round.

Yes :smile:

**Pull request merged**
