### PR TITLE
labwc.pot: update translation template for 71b2b5a

### LINKED ISSUE #2157: 71b2b5a introduces a new string for translation
`po/labwc.pot` needs updating.

@stefonarch I gather that weblate will take care of the rest.

### PR DESCRIPTION
**Pull request by 01micko**
fixes #2157

### CODE REVIEW

**Comment by 01micko** [comment]
Oh dear, wrong commit. Fix shortly.

**Comment by stefonarch** [comment]
Btw what is "go there..." about?

**Comment by 01micko** [comment]
Not quite sure but I noticed it untranslated. @droc12345 can answer you.

**Comment by 01micko** [comment]
@droc12345 just tried it out.. rather cool!

**Comment by stefonarch** [comment]
Hm, didn't quite understand what happens with "go there..." and I noticed an empty space, maybe not the right place to discuss this.
immagine

**Comment by droc12345** [comment]
stefonarch,  I opened an issue, #2159

I will leave it there, just in case it happens again.

**Comment by johanmalm** [comment]
Thanks.

**Pull request merged**
