### PR TITLE
Mouse constraints implementation

### PR DESCRIPTION
**Pull request by Ph42oN**
I looked how this was done in sway and did it in labwc. This fixes issues #339 and #534 for me.

### CODE REVIEW

**Comment by Consolatis** [comment]
First of all: thanks for working on this.

I had a quick test and it doesn't seem to confine the cursor correctly, it can be tested via the [example application here](https://github.com/labwc/labwc/issues/475#issuecomment-1277924728). It also breaks the same test with `--locked`.

I had a quick try in figuring out how all this is supposed to work but failed. I might look into this some more during the next days, if somebody else wants to work on this feel free.

**Comment by johanmalm** [comment]
Thanks both. I’m just having a busy few days, so not able to look at it just now.

**Comment by Ph42oN** [comment]
Looks like it actually only makes cursor stay within window area for fullscreen applications. I did this in simpler way than it was done in sway, so i think there is something missing.

**Comment by Ph42oN** [comment]
I made constraints work for windowed.

**Comment by Consolatis** [comment]
This looks very promising!

It is a bit hard to test on a nested instance as that one uses absolute coordinates but this seems to completely fix the pointer constraints for windows. Nice work.

I added back the lock confinement and will test later on an actual DRM session.
More testers would be welcome.

We may need to restore the pixman dependency that we dropped some time ago but that can be handled once this is merged.

**Comment by johanmalm** [comment]
LGTM
Have tested with @Consolatis 's test application https://github.com/labwc/labwc/issues/475#issuecomment-1277924728
Agree we should squash.

**Comment by Consolatis** [comment]
Cleaned up the history, this seems ready to go.

Thanks a bunch @Ph42oN!

**Comment by johanmalm** [comment]
Thank you both. Really nice :smile:

**Pull request merged**
