### PR TITLE
view: only add foreign-handle for root toplevel

### PR DESCRIPTION
**Pull request by johanmalm**
Welcome thoughts / review.

### CODE REVIEW

**Comment by Consolatis** [comment]
I think we should set the parent to the toplevel handle of the parent instead. Then it would be panel policy if and how they show handles that have a parent (e.g. grouping them together, hiding them, showing them as every other handle).

**Comment by johanmalm** [comment]
> I think we should set the parent to the toplevel handle of the parent instead. Then it would be panel policy if and how they show handles that have a parent (e.g. grouping them together, hiding them, showing them like any other handle).

I couldn't work out how to do it. :blush:

**Comment by Consolatis** [comment]
Shouldn't it just be something like this? Not tested at all.
```c
/* Copied from xdg_toplevel_view_get_root() */

struct wlr_xdg_toplevel *toplevel = xdg_toplevel_from_view(view);
if (toplevel->parent) {
	struct wlr_xdg_surface *surface = toplevel->parent->base;
	struct view *parent = surface->data;
	if (parent->toplevel.handle) {
		wlr_foreign_toplevel_handle_v1_set_parent(
			view->toplevel.handle, parent->toplevel.handle);
	}
}
```

**Comment by johanmalm** [comment]
@Consolatis Thanks for that tip. Worked a treat.
Ready to go.

**Comment by Consolatis** [comment]
I'd like to look into the lifecycle management before merging this to make sure we don't accidentally leave a dangling pointer hanging somewhere in wlroots. Will likely have done that until tomorrow.

**Comment by Consolatis** [comment]
When a toplevel is destroyed, wlroots loops over all toplevels and resets the parent to `NULL` if it is currently set to the destroying toplevel (and informs the clients about it). So this should be safe. Thanks for the PR :)

**Pull request merged**
