### PR TITLE
IME: support IME popup

### PR DESCRIPTION
**Pull request by tokyo4j**
Complements #1548 with IME popup.

To get the position of the layer surface focused by seat, I set `wlr_surface->data` to `lab_layer_surface->scene_layer_surface->tree` or `lab_layer_popup->scene_tree`. But I'm not sure this is the right way to do it.
You can test IME popup on layer surface by running `wofi --show drun` without setting `GTK_IM_MODULE`.

Sway's implementation here: swaywm/sway#7226
I made some documentation on IME: labwc/labwc.github.io#49

Demo on Alacritty:
ime

### CODE REVIEW

**Comment by johanmalm** [comment]
This looks great. Nice contribution.

Let me check those user-data fields. We ought to document (throughout the code-base) what we set them to and where/why. There could be a potential conflict there. Too tired tonight though :smile:

**Comment by johanmalm** [comment]
Thanks for this patch. LGTM. Will go for merge.

> I set wlr_surface->data to lab_layer_surface->scene_layer_surface->tree or lab_layer_popup->scene_tree. But I'm not sure this is the right way to do it.

Yes, I think that's the way to do it.

To build confidence, I've reviewed the other user-data variables we set and put them in the table below. The main thing is that there isn't a clash (which there isn't).

```
| user data                             | used for           | file                   |
|---------------------------------------|--------------------|------------------------|
| `wlr_popup->base->xdg_surface->data`  | `wlr_scene_node`   | xdg-popup.c:124        |
| `wlr_xdg_surface->data`               | `view`             | xdg.c:765              |
| `wlr_xdg_surface->surface->data`      | `wlr_scene_tree`   | xdg.c:777              |
| `wlr_xwayland_surface->data`          | `view`             | xwayland.c:857         |
| `wlr_output->data`                    | `output`           | output.c:317           |
| `wlr_scene_node->data`                | `node_descriptor`  | node.c:34              |
| `wlr_input_device->data`              | `input`            | seat.c:453             |
| `wlr_tablet->data`                    | `tablet`           | input/tablet.c:137     |
| `wlr_tablet->data`                    | `tablet`           | input/tablet_pad.c:42  |
```

**Comment by tokyo4j** [comment]
One thing I didn't address is showing IME popup at text-input on subsurfaces.
In my implementation, if both `wlr_xdg_surface_try_from_wlr_surface` and `wlr_layer_surface_v1_try_from_wlr_surface` fails, the popup is placed at (0, 0).
I'll address it later if there's any real-world applications that cause it.

**Comment by johanmalm** [comment]
Really nice work btw. Great to add support for this.

**Pull request merged**
