### PR TITLE
cursor: prevent press on layer-subsurface from cancelling popup grab

### PR DESCRIPTION
**Pull request by johanmalm**
Hopefully fixes: #1030

Would appreciate some testing for unintended consequences.

### CODE REVIEW

**Comment by Tamaranch** [comment]
I can confirm it fixes the issue, apparently without side effects.

**Comment by 01micko** [comment]
No apparent side effects running `labwc/sfwbar` either.

**Comment by Consolatis** [comment]
Didn't see any issues either. LGTM, nice PR :)

**Comment by johanmalm** [comment]
> Edit: One thing I discovered though: Even without requesting keyboard focus, panels now react to `ESC` to close context menus. Which may or may not be a good thing. I am not sure. To fix that we'd have to also supply (or get) the underlying layershell surface and then check that for its keyboard interactivity setting. I kind of like this though for panels.. it works similar to `ON_DEMAND` now.

Yes, great observation/analysis. I did ponder this. Agree with you though - let's go as is. If it becomes a problem we can find top-parent and check on-demand.

**Comment by johanmalm** [comment]
And thanks everyone for testing :smile:

**Pull request merged**
