### PR TITLE
Add All context for mouse events

### PR DESCRIPTION
**Pull request by spl237**
Fairly trivial change to add an "All" context for mouse bindings which need to be handled irrespective of the mouse pointer location, as discussed at https://github.com/labwc/labwc/issues/1767

Tested locally - seems to work fine for me!

### CODE REVIEW

**Comment by tokyo4j** [comment]
Documentation is missing. I suggest something like:
```diff
diff --git a/docs/labwc-config.5.scd b/docs/labwc-config.5.scd
index acc59ada..2c55763a 100644
--- a/docs/labwc-config.5.scd
+++ b/docs/labwc-config.5.scd
@@ -559,6 +559,7 @@ extending outward from the snapped edge.
 	  through to the application.
 	- Desktop: The desktop background, where no windows are present.
 	- Root: A synonym for Desktop (for compatibility).
+	- All: Any of the contexts described above.
 
 	Supported mouse *buttons* are:
 	- Left
```

**Comment by spl237** [comment]
> Documentation is missing. I suggest something like:
> 
> ```diff
> diff --git a/docs/labwc-config.5.scd b/docs/labwc-config.5.scd
> index acc59ada..2c55763a 100644
> --- a/docs/labwc-config.5.scd
> +++ b/docs/labwc-config.5.scd
> @@ -559,6 +559,7 @@ extending outward from the snapped edge.
>  	  through to the application.
>  	- Desktop: The desktop background, where no windows are present.
>  	- Root: A synonym for Desktop (for compatibility).
> +	- All: Any of the contexts described above.
>  
>  	Supported mouse *buttons* are:
>  	- Left
> ```
> 
> Feel free to enhance my words. I'm poor at writing English.

Good idea - thanks for the suggestion!

It's not quite accurate to say that 'All' is any of the contexts, because it also includes things like the desktop background which isn't covered by any of the existing contexts, so I have described it as "Anywhere on the screen".

**Comment by droc12345** [comment]
All: Supersedes of all of the other contexts, plus places where context might not apply.

**Comment by Consolatis** [comment]
> On testing, scrolling over a window without the modifier key held causes the window to scroll; scrolling with the modifier held only triggers the desired mouse binding - so this appears to do what would be expected.

This is likely only because of the `Scroll` bindings, if you try the same with a `Press` binding I assume the click will go through to the application. I think this needs to update `consumed_by_frame_context`.

**Comment by spl237** [comment]
> > On testing, scrolling over a window without the modifier key held causes the window to scroll; scrolling with the modifier held only triggers the desired mouse binding - so this appears to do what would be expected.
> 
> This is likely only because of the `Scroll` bindings, if you try the same with a `Press` binding I assume the click will go through to the application. I think this needs to update `consumed_by_frame_context`.
> 
Does that change do the right thing?

**Comment by Consolatis** [comment]
> > > On testing, scrolling over a window without the modifier key held causes the window to scroll; scrolling with the modifier held only triggers the desired mouse binding - so this appears to do what would be expected.
> > 
> > 
> > This is likely only because of the `Scroll` bindings, if you try the same with a `Press` binding I assume the click will go through to the application. I think this needs to update `consumed_by_frame_context`.
> 
> Does that change do the right thing?

Theoretically yes. But it looks like labwc doesn't really do the right thing in regards to eating the `Release` event for `Press` mousebinds in the `Frame` (and now `All` context). `Click` on the other side works (but only executes the first matching binding found). That is somewhat outside the scope of this PR though and needs some work.

**Comment by droc12345** [comment]
Why would you ever not want the mouse press, scroll, modifier, etc in mousebind to be consumed, ie never pass to whatever is underneath?

**Comment by johanmalm** [comment]
LGTM. Have tested with config below (after rebasing onto `master`). Works well.

```
  <mouse>
    <context name="All">
      <mousebind direction="W-Up" action="Scroll">
        <action name="ZoomIn"/>
      </mousebind>
      <mousebind direction="W-Down" action="Scroll">
        <action name="ZoomOut"/>
      </mousebind>
    </context>
  </mouse>
```

**Comment by spl237** [comment]
Excellent - many thanks!

**Pull request merged**
