### PR TITLE
view: macro-ize signal/listener connection

### PR DESCRIPTION
**Pull request by jlindgren90**
@Consolatis mentioned this as an idea in #814. It seems worth pursuing to me, since it makes the code a bit more readable IMHO (and forces us to be consistent with event handler function names).

No functional change.

### CODE REVIEW

**Comment by jlindgren90** [comment]
```
src/xwayland.c:785: CHECK: Macro argument 'name' may be better as '(name)' to avoid precedence issues
```
This seems to be a false-positive in `scripts/check` (parentheses cannot be added around struct field names). Not sure of how to best address this.

**Comment by Consolatis** [comment]
Could we have that defined in some header instead?
Something like `CONNECT_SIGNAL()`?

I don't think there is a reason to have xwayland-unmanaged.c prefix the handlers with `unmanaged_`, those are static functions anyway.

> This seems to be a false-positive in scripts/check (parentheses cannot be added around struct field names). Not sure of how to best address this.

I guess we could roll out the dark magic (e.g. void pointer of dest + offsetof() from name) to have it work for the `dest` part. But the function name part for the handler would still break and type casting is also missing. Easier solution: we just remove that check from checkpatch.pl. CC @johanmalm

**Comment by Consolatis** [comment]
Btw, didn't you add a function doing basically the same for the 0.17 surface associate events?
That would be an alternative as all handlers share the same signature.

**Comment by johanmalm** [comment]
I like this in principle.

Agree with putting macros in header and force commonality (i.e. remove `unmanaged_`).
Other than that LGTM.


Suggest disabling check with:

```
diff --git a/scripts/checkpatch.pl b/scripts/checkpatch.pl
index e6b701f..53d6d26 100755
--- a/scripts/checkpatch.pl
+++ b/scripts/checkpatch.pl
@@ -64,6 +64,7 @@ my @ignore = (
 	"PREFER_FALLTHROUGH",
 	"INITIALISED_STATIC",
 	"UNNECESSARY_ELSE",
+	"MACRO_ARG_PRECEDENCE",
 );
 my $help = 0;
 my $configuration_file = ".checkpatch.conf";
```

**Comment by johanmalm** [comment]
Reminds me a bit of `QObject::connect()`

**Comment by jlindgren90** [comment]
> Btw, didn't you add a function doing basically the same for the 0.17 surface associate events? That would be an alternative as all handlers share the same signature.

Not really - only map/unmap are handled in a separate function. The macro is still useful for all the other signals, including the new associate/dissociate.

**Comment by jlindgren90** [comment]
> Reminds me a bit of `QObject::connect()`

Yes, definitely inspired by that :)

**Comment by jlindgren90** [comment]
Partially updated - I will return to this later.

OK to rename `common/array-size.h` to `common/macros.h`? Having one header per macro seems excessive.

**Comment by Consolatis** [comment]
> OK to rename `common/array-size.h` to `common/macros.h`? Having one header per macro seems excessive.

No issues with that from my side.

**Comment by jlindgren90** [comment]
Should be all set now.

**Comment by Consolatis** [comment]
> > OK to rename `common/array-size.h` to `common/macros.h`? Having one header per macro seems excessive.
> 
> No issues with that from my side.

Actually we could also move the `MIN()` and `MAX()` macros there. Everything we can out of `labwc.h` is a good thing in my book. We don't have to do that in this PR though.

**Comment by jlindgren90** [comment]
Style check was failing due to an indentation issue, fixed now.

**Comment by jlindgren90** [comment]
Moved MIN and MAX as well.

**Comment by johanmalm** [comment]
Be careful with min-max, they clash with the same macros names in cairo.h
We could make max/min lower case to avoid the clash in future

**Comment by jlindgren90** [comment]
I have `MIN/MAX` in glib/gmacros.h rather than cairo.h. But I think we discussed before (when adding them to labwc.h) and decided that the `#ifndef` guard around ours was safe enough. The glib macros are identical to ours and will always take precedence if included (before or after ours) because gmacros.h does `#undef MIN/MAX` beforehand.

**Comment by jlindgren90** [comment]
Incidentally, #1005 recently added static `min/max` functions in snap.c. Probably fine as long as we stick to UNIX-like platforms, but `min/max` (lowercase) are macros defined in windows.h and so naming functions `min/max` is non-portable. That bit us in Audacious years ago.

**Comment by johanmalm** [comment]
> I have `MIN/MAX` in glib/gmacros.h rather than cairo.h. But I think we discussed before (when adding them to labwc.h) and decided that the `#ifndef` guard around ours was safe enough. The glib macros are identical to ours and will always take precedence if included (before or after ours) because gmacros.h does `#undef MIN/MAX` beforehand.

You’re right. Ignore my last :smile:

capital MIN MAX and ifndef makes sense

**Pull request merged**
