### PR TITLE
scene-helpers: use pending_commit_damage, chases wlr!4253

### PR DESCRIPTION
**Pull request by Consolatis**
Using the output damage_ring for early out will break VRR in direct scanout mode. The reason being that the damage_ring will be completely ignored in that mode so we need to check `output->pending_commit_damage` instead. This matches with what wlroots has been doing since [0] and it was missed in the initial port to wlroots 0.18.x.

However, that would then break the magnifier which only adds its damage to the damage ring. After some discussion with the wlroots devs we came up with a solution that should work for both, wlroots 0.18.0 and when [1] is backported to 0.18.1.

Note that even with this PR, VRR in direct scanout mode is broken in 0.18.0 from the wlroots side and will be fixed once [1] is backported to the 0.18 branch and 0.18.1 is released.

Fixes: #2078

[0] https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4253
[1] https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4753

---

I'd strongly vote for having this be part of 0.8.0 because otherwise VRR in direct scanout mode will keep being broken even if wlroots releases 0.18.1.

Note, only tested this nested:
- on the current 0.18 branch
- on a local 0.18 branch with cherry-picked backport of [1]

It would be great if somebody could test this on the DRM side but I don't expect any issues there.

### CODE REVIEW

**Comment by Nefsen402** [comment]
> I'd strongly vote for having this be part of 0.8.0

Note that the magnifier will be broken when the backport happens. Needs to be in NEWS and part of this release.

**Comment by Consolatis** [comment]
> > I'd strongly vote for having this be part of 0.8.0
> 
> Note that the magnifier will be broken when the backport happens. Needs to be in NEWS and part of this release.

Why is that? I tested it with https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4753 backported to 0.18.

**Comment by Nefsen402** [comment]
Because we're not updating `pending_commit_damage` from the current labwc release, as soon as the backport comes through, we would be submitting bad damage to the backend as it won't correctly add the damage to `pending_commit_damage`.

**Comment by Consolatis** [comment]
> Because we're not updating `pending_commit_damage` from the current labwc release, as soon as the backport comes through, we would be submitting bad damage to the backend.

Right, but the current labwc release is based on wlroots 0.17. And with this PR we do add the magnifier damage to `pending_commit_damage` so I am slightly confused.

**Comment by Nefsen402** [comment]
Ah, I thought a labwc release already exists of 0.18. Nevermind

**Comment by johanmalm** [comment]
LGTM. I can test tomorrow night.

**Comment by Consolatis** [comment]
Had a chance for a quick test of this PR with the 0.18 branch of wlroots and https://gitlab.freedesktop.org/bl4ckb0ne/wlroots/-/tree/backport-0.18.1 with the mentioned backports included on DRM and everything seems fine. I don't have anything supporting VRR so I am not sure if that is fixed on the backport-0.18.1 branch with this PR or not.

**Comment by johanmalm** [comment]
I have tested on DRM against `0.18.0` as well as `0.18.0` with the `4753` commits cheery-picked.
Have tested Zoom and fullscreen applications. All works fine. Can't test fullscreen.

**Comment by johanmalm** [comment]
LGTM. Thanks for this.

**Pull request merged**
