### PR TITLE
xwayland: Keep view->xwayland_surface and view->surface in sync

### PR DESCRIPTION
**Pull request by Consolatis**
This will hopefully fix
- #317

@acoolstraw @BitterlyIronic testing appreciated.

### CODE REVIEW

**Comment by BitterlyIronic** [comment]
Been running this for the past day and I haven't seen the empty window issue crop up in that time.

**Comment by johanmalm** [comment]
> Been running this for the past day and I haven't seen the empty window issue crop up in that time.

Thanks for feedback. I vote for merge if @Consolatis is content

**Comment by Consolatis** [comment]
Simplified the code a bit:
https://github.com/labwc/labwc/blob/a0afd443f59b6b9cab1563d3b963e9ecb7af98e4/src/xwayland.c#L99-L108

@johanmalm would be great if you could look over it again, there shouldn't actually be any race conditions left.

Thus the new `assert()` should never trigger:
- on map
  - when `view->surface` changed
    - when `view->surface` is set
      - remove the destroy handler
    - assign new `view->surface`
    - add the destroy handler for the new surface
- on `view->xwayland_surface` destroy
  - when `view->surface` set
    - remove the destroy handler
    - set `view->surface` to `NULL`
- on `view->surface` destroy
  - assert `view->surface` == surface being destroyed
  - remove the destroy handler
  - set `view->surface` to `NULL`

**Comment by johanmalm** [comment]
Thanks!

**Pull request merged**
