### PR TITLE
src/xdg.c: spawn initially maximized views on cursor output

### PR DESCRIPTION
**Pull request by Consolatis**
\+ add a small comment whats going on there.

@jlindgren90 pointing out errors and thoughts about the "Open question" part would be much appreciated.

### CODE REVIEW

**Comment by jlindgren90** [comment]
I can't discuss in too much depth right now but initial thoughts are:
1. This probably works but does seem a bit roundabout. In my own master branch, I went in a different direction of setting view->output directly before calling view_maximize(), and modifying view_maximize() to use view->output.
2. We probably need a similar fix for fullscreen as well.

**Comment by Consolatis** [comment]
This pattern of modifying `view->current.{x,y}` is used in `xwayland.c` and `xdg.c` and basically just forces `view_discover()` to use a defined output.

I completely agree that this is a complete hack and abuse of implementation internals.
In the meantime, due to our current use of this pattern and the missing alternative, what do you think about creating a function like `view_move_to_output(struct view *view, struct ouput *output)` so we confine that pattern into a single place?

Then the current users could use that function instead and all the hacky details are hidden from the outside until we have a better strategy to deal with it.

> We probably need a similar fix for fullscreen as well.

Yes, indeed. If everbody agrees with the `view_move_to_output()` idea I could add that to `request_fullscreen()` as well and also replace the existing uses with the new function call.

**Comment by jlindgren90** [comment]
Sounds fine to me as a short-term fix.

**Comment by johanmalm** [comment]
Just looking at this fairly quickly, so might be barking up the wrong tree, but would something like this work:

In `handle_request_maximize()` if `(!view->been_mapped)` then pass store_natural_geometry=false to `view_maximize()`.

Then in `xdg_toplevel_view_map()` in the `!view->been_mapped` section check for view->maximized and set the natural geometry there based on `output_usable_area_from_cursor_coords()` and `xdg_surface->current.geometry.{width,height}` (because in the map handler we are allowed to read those variables).

**Comment by jlindgren90** [comment]
For storing the natural geometry, another idea would be to set view.pending to the surface width/height prior to calling view_maximize(). That's what we do for XWayland views (see ensure_initial_geometry()). (XWayland also sets view.current but I don't think that's necessary anymore.)

**Comment by Consolatis** [comment]
> In `handle_request_maximize()` if `(!view->been_mapped)` then pass store_natural_geometry=false to `view_maximize()`.
> Then in `xdg_toplevel_view_map()` in the `!view->been_mapped` section check for view->maximized and set the natural geometry there based on `output_usable_area_from_cursor_coords()` and `xdg_surface->current.geometry.{width,height}`

That would set the natural geometry to the maximized width / height, e.g. when the user would then un-maxmize foot it would basically not change position or size but just not be maximized anymore.

> another idea would be to set view.pending to the surface width/height prior to calling view_maximize().

Just tried that: `[../src/xdg.c:201] handle_request_maximize: Set pending to 0x0`
So it seems there are no previous commit calls (by foot at least) which we could use to define the natural geometry.

**Comment by jlindgren90** [comment]
> Just tried that: `[../src/xdg.c:201] handle_request_maximize: Set pending to 0x0` So it seems there are no previous commit calls (by foot at least) which we could use to define the natural geometry.

Okay, thanks for checking. I guess I am thinking in X11 terms and relatively ignorant of how xdg-shell works in this area.

**Comment by Consolatis** [comment]
I've added a new `view_move_to_output(view, output, /* apply_geometry */)` function and replaced the usage of the position hack in xwayland.c and xdg.c. Ignore the build warning for Void, its unrelated to the PR.

Turns out that function was actually pretty easy to enhance to allow moving usual views to different outputs as well (which is what the `apply_geometry` arg is for). In case somebody wants to test that: I've bound the new function to the `Debug` action.
It will move the active view to the output where the cursor is currently on while preserving the state (e.g. maximized / snapped to edge / fullscreen). This might become pretty handy when using VNC clients or similar which only have access to a single screen. I recommend not trying that with region tiled views right now though as the region they are using is attached to a single output and thus need to be replaced with the same region on the target output. Will implement that later.

This branch is based on two more commits which fix issues I detected along the way, I've split those into their own PRs and will rebase this branch once they are merged. Only the last two commits are related to this PR.

**Comment by Consolatis** [comment]
Suggestions on how to move forward?
Just adding `struct output` to `view_maximize()` and using output_from_cursor in the request_maximize `!view->been_mapped` handler?

**Comment by jlindgren90** [comment]
> Suggestions on how to move forward? Just adding `struct output` to `view_maximize()` and using output_from_cursor in the request_maximize `!view->been_mapped` handler?

Sounds good to me, at least short-term.

**Comment by Consolatis** [comment]
Replaced by
- #798

**Pull request closed without merging**
