### PR TITLE
menu: move ToggleOmnipresent to workspaces

### PR DESCRIPTION
**Pull request by johanmalm**
...and rename it to "Always on Visible Workspace"

Issue: #1316

### CODE REVIEW

**Comment by Consolatis** [comment]
LGTM in principle, misses updating the .pot file (and individual `.po` files for the `AlwaysOnTop` -> `Always On Top` change).

**Comment by 01micko** [comment]
Well, `po` are for the translators to add using `pot` as a template, so `po` is not necessarily programmer's responsibilty.
Anyway here it is:

 <details labwc.pot>
<summary>updated file labwc.pot based on this PR</summary>

```
# Labwc pot file
# Copyright (C) 2023
# This file is distributed under the same license as the labwc package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: labwc\n"
"Report-Msgid-Bugs-To: https://github.com/labwc/labwc/issues\n"
"POT-Creation-Date: 2023-01-02 11:22+1000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: src/menu/menu.c:698
msgid "Reconfigure"
msgstr ""

#: src/menu/menu.c:700
msgid "Exit"
msgstr ""

#: src/menu/menu.c:716
msgid "Minimize"
msgstr ""

#: src/menu/menu.c:718
msgid "Maximize"
msgstr ""

#: src/menu/menu.c:720
msgid "Fullscreen"
msgstr ""

#: src/menu/menu.c:722
msgid "Decorations"
msgstr ""

#: src/menu/menu.c:724
msgid "Always on Top"
msgstr ""

#: src/menu/menu.c:729
msgid "Move left"
msgstr ""

#: src/menu/menu.c:736
msgid "Move right"
msgstr ""

#: src/menu/menu.c:741
msgid "Always on Visible Workspace"
msgstr ""

#: src/menu/menu.c:744
msgid "Workspace"
msgstr ""

#: src/menu/menu.c:747
msgid "Close"
msgstr ""
```
</details>

**Comment by Consolatis** [comment]
> Well, `po` are for the translators to add using `pot` as a template, so `po` is not necessarily programmer's responsibilty.

Right, but in this case the `msgid` was changed for `AlwaysOnTop` which already has proper translations. So I'd assume all that need to be done for that case is to also update the msgid in all `.po` files.

Thanks for the `.pot` update.

**Comment by 01micko** [comment]
> So I'd assume all that need to be done for that case is to also update the msgid in all `.po` files.

I see your point, but a translation also needs to be added for "Always on Visible Workspace" which requires attention of the translators. Perhaps we should @ping them all when a change like this occurs, which will be every time there is an addition or change of phrase. Buit I think a few days out from release is a better idea, so that a fresh release looks more professional.

Part of the reason I put in the `--add-comments` option to the `xgettext` command was for ease of reference; such as the file:line number. I notice that _all_ of the current `po` files are out of sync with current master branch `pot` file which is understandable due to recent activity in moving to wlroots-17.x and the recent menu additions. However, _all_ of the `po` files are in sync with each other. Looks like we have a good bunch of translators :)

**Comment by stefonarch** [comment]
Just a question dropping in here: how are translations handled, with normal PRs?
I've added already several other applications to our [weblate](https://translate.lxqt-project.org/) instance, I could add  labwc too if that would be ok for you, we have over 300 tranlators signed up.

**Comment by johanmalm** [comment]
> LGTM in principle, misses [updating](https://github.com/labwc/labwc/blob/master/CONTRIBUTING.md#native-language-support) the `.pot` file (and individual `.po` files for the `AlwaysOnTop` -> `Always on Top` change).

Done.

@01micko - Thanks. Having that `xgettext` line in `CONTRIBUTING.md` helps.
I've updated the pot file now - and also the Swedish translation.

@stefonarch - Adding us weblate would be great. Wasn't aware of it.

Ready to go from my perspective.

**Comment by Consolatis** [comment]
:)

**Pull request merged**
