### PR TITLE
view: stay fullscreen when view's output is disconnected

### PR DESCRIPTION
**Pull request by jlindgren90**
I intended to fix this quite some time ago but didn't get around to it.

I don't think there's any good reason why we need to un-fullscreen a view when its output is disconnected. We can handle it the same as a maximized view, and move it to a new output (remaining fullscreen) or, if all outputs are disconnected, just leave it as-is.

This is helpful for a media-center use-case, where you have just one view (e.g. Kodi) fullscreen all the time, but the TV might appear to be disconnected if you switch it to a different source.

Tested with a couple different scenarios:

1. Single output disconnected and re-connected: view stayed fullscreen.
2. Secondary output disconnected: view stayed fullscreen but moved to the primary output, and the layer-shell panel on that output was hidden as expected. When the secondary output was re-connected, the view was moved back (still fullscreen) and the panel on the primary appeared again.

Fixes: #864

### CODE REVIEW

**Comment by Consolatis** [comment]
No objections from my side, code LGTM on the first glance but I didn't look deeper into it nor tested.

CC @ahesford

**Comment by ahesford** [comment]
This seems to work as advertised in my dual-head configuration (which throws a fast disconnect-reconnect sequence when a display resumes from sleep) that motivated the geometry-restoration feature in the first place.

However, it poses a question of intent. While there is no question that it would be desirable to restore full-screen (or even maximized) states when restoring a window *to its original display*, is it generally desirable to keep a window fullscreen when it is moved to another display? There might be multiple full-screen windows across multiple displays, each of which may have a unique geometry, and it may be preferable to demote a full-screen window when its display is lost rather than have it compete with whatever has been assigned to a still-active output.

To get a "proper" feel should the answer be that windows should be restored to natural geometry when assigned on a new output, we could simply save a last-fullscreen state along with last geometry, and re-apply the fullscreen mode when the last geometry would be restored on output layout changes.

**Comment by jlindgren90** [comment]
> is it generally desirable to keep a window fullscreen when it is moved to another display?

I suppose it comes down to personal preference, but for me, yes. To me, full screen is a user-requested state that the WM should not automatically change unless necessary, and also it has more to do with the content/purpose of a window than what display it's on.

Use-case: I'm watching a movie on a laptop docked to a TV, and undock to go to a different room. If I'm still watching the movie, I still want it full screen on the laptop. If I'm done watching, I'll pause and/or close the player manually.

**Comment by ahesford** [comment]
That's a reasonable position, and in that case, this PR seems to work as expected.

**Comment by Consolatis** [comment]
> There might be multiple full-screen windows across multiple displays, each of which may have a unique geometry, and it may be preferable to demote a full-screen window when its display is lost rather than have it compete with whatever has been assigned to a still-active output.

Should we unfullscreen if there is already a fullscreen view on the new output?

**Comment by ahesford** [comment]
I don't have a strong opinion here, because the only time I ever full-screen a window is when I'm watching a video in mpv, and there's only ever a single window in that case.

**Comment by jlindgren90** [comment]
> Should we unfullscreen if there is already a fullscreen view on the new output?

My vote would be no - this seems like trying to be too "smart" and guess what the user wants when we don't really know. Also there is nothing wrong with having two full screen views - you can still Alt-Tab between them just fine. I do this sometimes on the "media center" PC.

**Comment by Consolatis** [comment]
Alright, going for the merge then. Thanks!

**Pull request merged**
