### PR TITLE
wip: Update for wlroots-git (0.16.0)

### PR DESCRIPTION
**Pull request by jlindgren90**
Various small updates needed to build labwc with the `master` branch of wlroots.  I plan on continuing to update this branch if/when wlroots makes additional breaking changes.

This isn't intended to be merged until wlroots 0.16.0 is released, but it may be useful to anyone else wanting to use labwc with a bleeding-edge version of wlroots.

**edit 2022/3/20:**
This is no longer needed for the `master` branch of labwc, but might still be useful if anyone is trying to build `v0.5` with a newer wlroots version.

### CODE REVIEW

**Comment by jlindgren90** [comment]
See also #211

**Comment by johanmalm** [comment]
Thanks

**Comment by droc12345** [comment]
src/output.c instead of removing the if (box) - line 1203 and following 
it could be changed to if (!wlr_box_empty(&box)) instead 
and this keeps the check for an empty or bad parm box and associated log message.

**Comment by johanmalm** [comment]
Thank you both. 
I've incorporated in the scene-graph branch (https://github.com/johanmalm/labwc/tree/scene) because we needed some new functions added after 0.15.1
Also added wlr_subcompositor_create() in server.c

**Comment by jlindgren90** [comment]
> See [d844f67](https://github.com/labwc/labwc/commit/d844f6798b2de509bef80c9f8148b5a975e98f6a) You might be able to cherry-pick

I was able to, thanks :)

**Comment by acoolstraw** [comment]
cool!

**Comment by acoolstraw** [comment]
why does the CI/build fail?

**Comment by jlindgren90** [comment]
I've been using only `master` lately and haven't updated this branch in quite a while, so I'm going to go ahead and close the merge request. I'll leave the `wlroots-git` branch up for now in case anyone wants to use it as a starting point for a new effort.

**Pull request closed without merging**
