### PR TITLE
Reload cursor theme and size on reconfigure

### PR DESCRIPTION
**Pull request by spl237**
As per https://github.com/labwc/labwc/issues/1587 - this seems to work for reloading cursor size and theme on a labwc --reconfigure.

### CODE REVIEW

**Comment by spl237** [comment]
Looks like something unrelated to this PR is broken in your Arch build system...

**Comment by spl237** [comment]
Now working!

**Comment by Consolatis** [comment]
Code looks good and seems to work fine. Thanks!

I wonder if we should also try to set the cursor image again so that users get instant feedback on reconfigure (if its currently a server side one or set via the cursor shape protocol, in comparison to the application setting it to a surface). But that can be its own PR, I'll try to look into this later.

**Comment by johanmalm** [comment]
Thanks!

**Pull request merged**
