### PR TITLE
Fix/view center

### PR DESCRIPTION
**Pull request by johanmalm**

### CODE REVIEW

**Comment by johanmalm** [comment]
I've tested with

- both SSD/CSD
- two physical monitors with different scales

**Comment by Consolatis** [comment]
Also had a quick test on a nested labwc:
- scale 0.5, 1 and 2
- SSD (`foot` wayland native)
- CSD (`d-feet` once with `GDK_BACKEND=x11` and once as wayland native)

All seem starting centered so once the `view->type` check is guarded by an `#if HAVE_XWAYLAND` this seems ready to go.

**Comment by heroin-moose** [comment]
^_^

**Comment by heroin-moose** [comment]
Works for me too.

**Pull request merged**
