### PR TITLE
xdg: try to handle missing set_window_geometry with Qt apps

### LINKED ISSUE #1194: Rarely, title-bar may not be resized on snapping to bottom/top by drag-and-drop
It happened here very randomly and rarely when I snapped a window to the bottom of the screen by dragging its title-bar and dropping it to the bottom edge. Fortunately, I took a screenshot:

bottom

I encountered it only once with the top edge and haven't seen it without drag-and-drop. However, I can't be sure that it's really related to drag-and-drop.

Sorry if it's already known or fixed in git; I use 0.6.5 and couldn't find it after a simple search.

### PR DESCRIPTION
**Pull request by jlindgren90**
Qt applications occasionally fail to call set_window_geometry after a configure request, but do correctly update the actual surface extent. This results in a mismatch between the window decorations (which follow the logical geometry) and the visual size of the client area. As a workaround, try to detect this case and ignore the out-of-date window geometry.

Should fix #1194.

### CODE REVIEW

**Comment by Consolatis** [comment]
LGTM, didn't test.

**Comment by Consolatis** [comment]
Could you add `Fixes: #1194` to the commit body? That makes it easier in the future to figure out the details of the change (including your debugging journey :)

**Comment by jlindgren90** [comment]
> Could you add `Fixes: #1194` to the commit body? That makes it easier in the future to figure out the details of the change (including your debugging journey :)

Sure, can do it later, or feel free to amend the commit and add that if you like.

**Comment by Consolatis** [comment]
added and force pushed

**Comment by Consolatis** [comment]
Merging due to confirmations that it fixes the issue in #1194.

**Pull request merged**
