### PR TITLE
rcxml: add core.autoEnableOutputs option

### PR DESCRIPTION
**Pull request by jlindgren90**
rcxml: add core.autoEnableOutputs option

Currently, labwc automatically enables outputs at startup and when new
outputs are connected. Make this behavior optional (but still enabled by
default).

With autoEnableOutputs disabled, tools such as kanshi can be used to
give finer-grained control of which outputs are enabled and when.
Personally, I use this to avoid re-enabling outputs that disconnect and
reconnect during powersave, but I can imagine other use-cases for it
also.

The first two commits address modesetting failures that are revealed by
this option but could also be merged separately.

### CODE REVIEW

**Comment by tokyo4j** [comment]
I don't even know what powersave is, but is it possible to test this PR on my setup?

**Comment by jlindgren90** [comment]
a.k.a. screensaver, DPMS off.

If you have kanshi set up to autostart, you can disable autoEnableOutputs and make sure that kanshi can still enable them correctly. And hotplugging a new display should enable it only if kanshi is running and configured to enable it.

**Comment by johanmalm** [comment]
LGTM

Optionally consider the following:

1. Embellish the commit message of `output: handle outputs that are enabled but not yet added` to give some context.
2. Add a note in the man page regarding how kanshi can be used with core.autoEnableOutputs=false. Maybe include an example kanshi config.
3. Adding a couple of sentences to the troubleshooting page on the homepage to help people find this option. I can't quite remember the use-case / context, but remember we've had several people reach out about it.

**Comment by tokyo4j** [comment]
I tested this PR, and found that the output geometry is not applied by kanshi for some reason. Not sure if this is kanshi's issue or labwc's issue.

<details><summary>`~/.config/kanshi/config`</summary>

```
profile my-home {
	output eDP-1 enable position 0,1080
	output DP-1  enable position 0,0
}
```

</details>

<details><summary>output of `WAYLAND_DEBUG=client kanshi`</summary>

```
[3956082.393] {Default Queue}  -> wl_display#1.get_registry(new id wl_registry#2)
[3956082.423] {Default Queue}  -> wl_display#1.sync(new id wl_callback#3)
[3956087.097] {Display Queue} wl_display#1.delete_id(3)
[3956087.117] {Default Queue} wl_registry#2.global(1, "wl_shm", 2)
[3956087.123] {Default Queue} wl_registry#2.global(2, "wl_drm", 2)
[3956087.126] {Default Queue} wl_registry#2.global(3, "zwp_linux_dmabuf_v1", 4)
[3956087.130] {Default Queue} wl_registry#2.global(4, "zcosmic_workspace_manager_v1", 1)
[3956087.132] {Default Queue} wl_registry#2.global(5, "ext_workspace_manager_v1", 1)
[3956087.135] {Default Queue} wl_registry#2.global(6, "zwlr_gamma_control_manager_v1", 1)
[3956087.138] {Default Queue} wl_registry#2.global(7, "zxdg_output_manager_v1", 3)
[3956087.141] {Default Queue} wl_registry#2.global(8, "zwlr_output_manager_v1", 4)
[3956087.145] {Default Queue}  -> wl_registry#2.bind(8, "zwlr_output_manager_v1", 4, new id [unknown]#4)
[3956087.149] {Default Queue} wl_registry#2.global(9, "wl_compositor", 5)
[3956087.151] {Default Queue} wl_registry#2.global(10, "wl_subcompositor", 1)
[3956087.155] {Default Queue} wl_registry#2.global(11, "wl_data_device_manager", 3)
[3956087.158] {Default Queue} wl_registry#2.global(12, "zwp_primary_selection_device_manager_v1", 1)
[3956087.161] {Default Queue} wl_registry#2.global(13, "zwp_input_method_manager_v2", 1)
[3956087.164] {Default Queue} wl_registry#2.global(14, "zwp_text_input_manager_v3", 1)
[3956087.167] {Default Queue} wl_registry#2.global(15, "wl_seat", 9)
[3956087.169] {Default Queue} wl_registry#2.global(16, "zwlr_virtual_pointer_manager_v1", 2)
[3956087.172] {Default Queue} wl_registry#2.global(17, "zwp_virtual_keyboard_manager_v1", 1)
[3956087.175] {Default Queue} wl_registry#2.global(18, "zwp_pointer_gestures_v1", 3)
[3956087.178] {Default Queue} wl_registry#2.global(19, "wp_cursor_shape_manager_v1", 1)
[3956087.181] {Default Queue} wl_registry#2.global(20, "xdg_wm_base", 3)
[3956087.184] {Default Queue} wl_registry#2.global(21, "xdg_activation_v1", 1)
[3956087.187] {Default Queue} wl_registry#2.global(22, "org_kde_kwin_server_decoration_manager", 1)
[3956087.190] {Default Queue} wl_registry#2.global(23, "zxdg_decoration_manager_v1", 1)
[3956087.193] {Default Queue} wl_registry#2.global(24, "wp_presentation", 1)
[3956087.196] {Default Queue} wl_registry#2.global(25, "zwlr_export_dmabuf_manager_v1", 1)
[3956087.199] {Default Queue} wl_registry#2.global(26, "zwlr_screencopy_manager_v1", 3)
[3956087.202] {Default Queue} wl_registry#2.global(27, "zwlr_data_control_manager_v1", 2)
[3956087.204] {Default Queue} wl_registry#2.global(28, "wp_security_context_manager_v1", 1)
[3956087.208] {Default Queue} wl_registry#2.global(29, "wp_viewporter", 1)
[3956087.211] {Default Queue} wl_registry#2.global(30, "wp_single_pixel_buffer_manager_v1", 1)
[3956087.213] {Default Queue} wl_registry#2.global(31, "wp_fractional_scale_manager_v1", 1)
[3956087.216] {Default Queue} wl_registry#2.global(32, "ext_idle_notifier_v1", 1)
[3956087.219] {Default Queue} wl_registry#2.global(33, "zwp_idle_inhibit_manager_v1", 1)
[3956087.222] {Default Queue} wl_registry#2.global(34, "zwp_relative_pointer_manager_v1", 1)
[3956087.225] {Default Queue} wl_registry#2.global(35, "zwp_pointer_constraints_v1", 1)
[3956087.228] {Default Queue} wl_registry#2.global(36, "zwlr_foreign_toplevel_manager_v1", 3)
[3956087.231] {Default Queue} wl_registry#2.global(37, "ext_foreign_toplevel_list_v1", 1)
[3956087.234] {Default Queue} wl_registry#2.global(38, "ext_session_lock_manager_v1", 1)
[3956087.237] {Default Queue} wl_registry#2.global(39, "wp_drm_lease_device_v1", 1)
[3956087.239] {Default Queue} wl_registry#2.global(40, "zwlr_output_power_manager_v1", 1)
[3956087.243] {Default Queue} wl_registry#2.global(41, "wp_tearing_control_manager_v1", 1)
[3956087.246] {Default Queue} wl_registry#2.global(42, "zwp_tablet_manager_v2", 1)
[3956087.248] {Default Queue} wl_registry#2.global(43, "zwlr_layer_shell_v1", 4)
[3956087.251] {Default Queue} wl_registry#2.global(44, "zxdg_exporter_v1", 1)
[3956087.254] {Default Queue} wl_registry#2.global(45, "zxdg_importer_v1", 1)
[3956087.268] {Default Queue} wl_registry#2.global(46, "zxdg_exporter_v2", 1)
[3956087.271] {Default Queue} wl_registry#2.global(47, "zxdg_importer_v2", 1)
[3956087.274] {Default Queue} wl_callback#3.done(2)
[3956087.390] {Default Queue} zwlr_output_manager_v1#4.head(new id zwlr_output_head_v1#4278190080)
[3956087.394] {Default Queue} zwlr_output_head_v1#4278190080.name("DP-1")
[3956087.397] {Default Queue} zwlr_output_head_v1#4278190080.description("Philips Consumer Electronics Company PHL 242E2F UHB2310004900 (DP-1)")
[3956087.400] {Default Queue} zwlr_output_head_v1#4278190080.physical_size(530, 300)
[3956087.403] {Default Queue} zwlr_output_head_v1#4278190080.make("Philips Consumer Electronics Company")
[3956087.406] {Default Queue} zwlr_output_head_v1#4278190080.model("PHL 242E2F")
[3956087.409] {Default Queue} zwlr_output_head_v1#4278190080.serial_number("UHB2310004900")
[3956087.412] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190081)
[3956087.415] {Default Queue} zwlr_output_mode_v1#4278190081.size(1920, 1080)
[3956087.418] {Default Queue} zwlr_output_mode_v1#4278190081.refresh(60000)
[3956087.420] {Default Queue} zwlr_output_mode_v1#4278190081.preferred()
[3956087.423] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190082)
[3956087.426] {Default Queue} zwlr_output_mode_v1#4278190082.size(1920, 1080)
[3956087.429] {Default Queue} zwlr_output_mode_v1#4278190082.refresh(74973)
[3956087.432] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190083)
[3956087.434] {Default Queue} zwlr_output_mode_v1#4278190083.size(1920, 1080)
[3956087.437] {Default Queue} zwlr_output_mode_v1#4278190083.refresh(60000)
[3956087.440] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190084)
[3956087.443] {Default Queue} zwlr_output_mode_v1#4278190084.size(1920, 1080)
[3956087.446] {Default Queue} zwlr_output_mode_v1#4278190084.refresh(59940)
[3956087.448] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190085)
[3956087.451] {Default Queue} zwlr_output_mode_v1#4278190085.size(1920, 1080)
[3956087.454] {Default Queue} zwlr_output_mode_v1#4278190085.refresh(50000)
[3956087.456] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190086)
[3956087.459] {Default Queue} zwlr_output_mode_v1#4278190086.size(1680, 1050)
[3956087.462] {Default Queue} zwlr_output_mode_v1#4278190086.refresh(59954)
[3956087.465] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190087)
[3956087.467] {Default Queue} zwlr_output_mode_v1#4278190087.size(1280, 1024)
[3956087.470] {Default Queue} zwlr_output_mode_v1#4278190087.refresh(75025)
[3956087.472] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190088)
[3956087.475] {Default Queue} zwlr_output_mode_v1#4278190088.size(1280, 1024)
[3956087.478] {Default Queue} zwlr_output_mode_v1#4278190088.refresh(60020)
[3956087.481] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190089)
[3956087.484] {Default Queue} zwlr_output_mode_v1#4278190089.size(1440, 900)
[3956087.486] {Default Queue} zwlr_output_mode_v1#4278190089.refresh(59887)
[3956087.489] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190090)
[3956087.492] {Default Queue} zwlr_output_mode_v1#4278190090.size(1280, 960)
[3956087.495] {Default Queue} zwlr_output_mode_v1#4278190090.refresh(60000)
[3956087.498] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190091)
[3956087.500] {Default Queue} zwlr_output_mode_v1#4278190091.size(1280, 800)
[3956087.503] {Default Queue} zwlr_output_mode_v1#4278190091.refresh(60000)
[3956087.506] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190092)
[3956087.509] {Default Queue} zwlr_output_mode_v1#4278190092.size(1280, 720)
[3956087.511] {Default Queue} zwlr_output_mode_v1#4278190092.refresh(60000)
[3956087.520] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190093)
[3956087.523] {Default Queue} zwlr_output_mode_v1#4278190093.size(1280, 720)
[3956087.525] {Default Queue} zwlr_output_mode_v1#4278190093.refresh(60000)
[3956087.528] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190094)
[3956087.531] {Default Queue} zwlr_output_mode_v1#4278190094.size(1280, 720)
[3956087.533] {Default Queue} zwlr_output_mode_v1#4278190094.refresh(59940)
[3956087.536] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190095)
[3956087.539] {Default Queue} zwlr_output_mode_v1#4278190095.size(1280, 720)
[3956087.541] {Default Queue} zwlr_output_mode_v1#4278190095.refresh(50000)
[3956087.544] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190096)
[3956087.547] {Default Queue} zwlr_output_mode_v1#4278190096.size(1024, 768)
[3956087.550] {Default Queue} zwlr_output_mode_v1#4278190096.refresh(75029)
[3956087.553] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190097)
[3956087.555] {Default Queue} zwlr_output_mode_v1#4278190097.size(1024, 768)
[3956087.558] {Default Queue} zwlr_output_mode_v1#4278190097.refresh(70069)
[3956087.561] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190098)
[3956087.563] {Default Queue} zwlr_output_mode_v1#4278190098.size(1024, 768)
[3956087.566] {Default Queue} zwlr_output_mode_v1#4278190098.refresh(60004)
[3956087.569] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190099)
[3956087.571] {Default Queue} zwlr_output_mode_v1#4278190099.size(832, 624)
[3956087.574] {Default Queue} zwlr_output_mode_v1#4278190099.refresh(74551)
[3956087.577] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190100)
[3956087.580] {Default Queue} zwlr_output_mode_v1#4278190100.size(800, 600)
[3956087.583] {Default Queue} zwlr_output_mode_v1#4278190100.refresh(75000)
[3956087.585] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190101)
[3956087.588] {Default Queue} zwlr_output_mode_v1#4278190101.size(800, 600)
[3956087.591] {Default Queue} zwlr_output_mode_v1#4278190101.refresh(72188)
[3956087.594] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190102)
[3956087.596] {Default Queue} zwlr_output_mode_v1#4278190102.size(800, 600)
[3956087.599] {Default Queue} zwlr_output_mode_v1#4278190102.refresh(60317)
[3956087.602] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190103)
[3956087.604] {Default Queue} zwlr_output_mode_v1#4278190103.size(800, 600)
[3956087.607] {Default Queue} zwlr_output_mode_v1#4278190103.refresh(56250)
[3956087.610] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190104)
[3956087.612] {Default Queue} zwlr_output_mode_v1#4278190104.size(720, 576)
[3956087.615] {Default Queue} zwlr_output_mode_v1#4278190104.refresh(50000)
[3956087.617] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190105)
[3956087.620] {Default Queue} zwlr_output_mode_v1#4278190105.size(720, 576)
[3956087.623] {Default Queue} zwlr_output_mode_v1#4278190105.refresh(50000)
[3956087.626] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190106)
[3956087.629] {Default Queue} zwlr_output_mode_v1#4278190106.size(720, 576)
[3956087.632] {Default Queue} zwlr_output_mode_v1#4278190106.refresh(50000)
[3956087.634] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190107)
[3956087.637] {Default Queue} zwlr_output_mode_v1#4278190107.size(720, 480)
[3956087.639] {Default Queue} zwlr_output_mode_v1#4278190107.refresh(60000)
[3956087.642] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190108)
[3956087.645] {Default Queue} zwlr_output_mode_v1#4278190108.size(720, 480)
[3956087.647] {Default Queue} zwlr_output_mode_v1#4278190108.refresh(60000)
[3956087.654] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190109)
[3956087.657] {Default Queue} zwlr_output_mode_v1#4278190109.size(720, 480)
[3956087.660] {Default Queue} zwlr_output_mode_v1#4278190109.refresh(59940)
[3956087.662] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190110)
[3956087.665] {Default Queue} zwlr_output_mode_v1#4278190110.size(720, 480)
[3956087.668] {Default Queue} zwlr_output_mode_v1#4278190110.refresh(59940)
[3956087.670] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190111)
[3956087.673] {Default Queue} zwlr_output_mode_v1#4278190111.size(720, 480)
[3956087.676] {Default Queue} zwlr_output_mode_v1#4278190111.refresh(59940)
[3956087.678] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190112)
[3956087.681] {Default Queue} zwlr_output_mode_v1#4278190112.size(640, 480)
[3956087.684] {Default Queue} zwlr_output_mode_v1#4278190112.refresh(75000)
[3956087.686] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190113)
[3956087.689] {Default Queue} zwlr_output_mode_v1#4278190113.size(640, 480)
[3956087.692] {Default Queue} zwlr_output_mode_v1#4278190113.refresh(72809)
[3956087.695] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190114)
[3956087.697] {Default Queue} zwlr_output_mode_v1#4278190114.size(640, 480)
[3956087.700] {Default Queue} zwlr_output_mode_v1#4278190114.refresh(66667)
[3956087.703] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190115)
[3956087.706] {Default Queue} zwlr_output_mode_v1#4278190115.size(640, 480)
[3956087.709] {Default Queue} zwlr_output_mode_v1#4278190115.refresh(60000)
[3956087.711] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190116)
[3956087.714] {Default Queue} zwlr_output_mode_v1#4278190116.size(640, 480)
[3956087.717] {Default Queue} zwlr_output_mode_v1#4278190116.refresh(59940)
[3956087.719] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190117)
[3956087.722] {Default Queue} zwlr_output_mode_v1#4278190117.size(640, 480)
[3956087.725] {Default Queue} zwlr_output_mode_v1#4278190117.refresh(59940)
[3956087.728] {Default Queue} zwlr_output_head_v1#4278190080.mode(new id zwlr_output_mode_v1#4278190118)
[3956087.730] {Default Queue} zwlr_output_mode_v1#4278190118.size(720, 400)
[3956087.733] {Default Queue} zwlr_output_mode_v1#4278190118.refresh(70082)
[3956087.736] {Default Queue} zwlr_output_head_v1#4278190080.enabled(1)
[3956087.738] {Default Queue} zwlr_output_head_v1#4278190080.current_mode(zwlr_output_mode_v1#4278190081)
[3956087.741] {Default Queue} zwlr_output_head_v1#4278190080.position(0, 0)
[3956087.744] {Default Queue} zwlr_output_head_v1#4278190080.transform(0)
[3956087.747] {Default Queue} zwlr_output_head_v1#4278190080.scale(1.00000000)
[3956087.750] {Default Queue} zwlr_output_head_v1#4278190080.adaptive_sync(0)
[3956087.753] {Default Queue} zwlr_output_manager_v1#4.head(new id zwlr_output_head_v1#4278190119)
[3956087.756] {Default Queue} zwlr_output_head_v1#4278190119.name("eDP-1")
[3956087.759] {Default Queue} zwlr_output_head_v1#4278190119.description("AU Optronics 0xDB8C (eDP-1)")
[3956087.761] {Default Queue} zwlr_output_head_v1#4278190119.physical_size(290, 170)
[3956087.764] {Default Queue} zwlr_output_head_v1#4278190119.make("AU Optronics")
[3956087.767] {Default Queue} zwlr_output_head_v1#4278190119.model("0xDB8C")
[3956087.770] {Default Queue} zwlr_output_head_v1#4278190119.mode(new id zwlr_output_mode_v1#4278190120)
[3956087.772] {Default Queue} zwlr_output_mode_v1#4278190120.size(1920, 1080)
[3956087.775] {Default Queue} zwlr_output_mode_v1#4278190120.refresh(60033)
[3956087.778] {Default Queue} zwlr_output_mode_v1#4278190120.preferred()
[3956087.780] {Default Queue} zwlr_output_head_v1#4278190119.mode(new id zwlr_output_mode_v1#4278190121)
[3956087.783] {Default Queue} zwlr_output_mode_v1#4278190121.size(1920, 1080)
[3956087.790] {Default Queue} zwlr_output_mode_v1#4278190121.refresh(40023)
[3956087.792] {Default Queue} zwlr_output_head_v1#4278190119.mode(new id zwlr_output_mode_v1#4278190122)
[3956087.795] {Default Queue} zwlr_output_mode_v1#4278190122.size(1680, 1050)
[3956087.798] {Default Queue} zwlr_output_mode_v1#4278190122.refresh(60033)
[3956087.801] {Default Queue} zwlr_output_head_v1#4278190119.mode(new id zwlr_output_mode_v1#4278190123)
[3956087.804] {Default Queue} zwlr_output_mode_v1#4278190123.size(1280, 1024)
[3956087.806] {Default Queue} zwlr_output_mode_v1#4278190123.refresh(60033)
[3956087.809] {Default Queue} zwlr_output_head_v1#4278190119.mode(new id zwlr_output_mode_v1#4278190124)
[3956087.812] {Default Queue} zwlr_output_mode_v1#4278190124.size(1440, 900)
[3956087.815] {Default Queue} zwlr_output_mode_v1#4278190124.refresh(60033)
[3956087.817] {Default Queue} zwlr_output_head_v1#4278190119.mode(new id zwlr_output_mode_v1#4278190125)
[3956087.820] {Default Queue} zwlr_output_mode_v1#4278190125.size(1280, 800)
[3956087.823] {Default Queue} zwlr_output_mode_v1#4278190125.refresh(60033)
[3956087.825] {Default Queue} zwlr_output_head_v1#4278190119.mode(new id zwlr_output_mode_v1#4278190126)
[3956087.828] {Default Queue} zwlr_output_mode_v1#4278190126.size(1280, 720)
[3956087.831] {Default Queue} zwlr_output_mode_v1#4278190126.refresh(60033)
[3956087.834] {Default Queue} zwlr_output_head_v1#4278190119.mode(new id zwlr_output_mode_v1#4278190127)
[3956087.837] {Default Queue} zwlr_output_mode_v1#4278190127.size(1024, 768)
[3956087.839] {Default Queue} zwlr_output_mode_v1#4278190127.refresh(60033)
[3956087.842] {Default Queue} zwlr_output_head_v1#4278190119.mode(new id zwlr_output_mode_v1#4278190128)
[3956087.845] {Default Queue} zwlr_output_mode_v1#4278190128.size(800, 600)
[3956087.847] {Default Queue} zwlr_output_mode_v1#4278190128.refresh(60033)
[3956087.850] {Default Queue} zwlr_output_head_v1#4278190119.mode(new id zwlr_output_mode_v1#4278190129)
[3956087.853] {Default Queue} zwlr_output_mode_v1#4278190129.size(640, 480)
[3956087.855] {Default Queue} zwlr_output_mode_v1#4278190129.refresh(60033)
[3956087.858] {Default Queue} zwlr_output_head_v1#4278190119.enabled(1)
[3956087.861] {Default Queue} zwlr_output_head_v1#4278190119.current_mode(zwlr_output_mode_v1#4278190120)
[3956087.863] {Default Queue} zwlr_output_head_v1#4278190119.position(0, 0)
[3956087.866] {Default Queue} zwlr_output_head_v1#4278190119.transform(0)
[3956087.869] {Default Queue} zwlr_output_head_v1#4278190119.scale(1.00000000)
[3956087.872] {Default Queue} zwlr_output_head_v1#4278190119.adaptive_sync(0)
[3956087.875] {Default Queue} zwlr_output_manager_v1#4.done(2)
applying profile 'my-home'
[3956087.883] {Default Queue}  -> zwlr_output_manager_v1#4.create_configuration(new id zwlr_output_configuration_v1#3, 2)
applying profile output 'eDP-1' on connected head 'eDP-1'
[3956087.890] {Default Queue}  -> zwlr_output_configuration_v1#3.enable_head(new id zwlr_output_configuration_head_v1#5, zwlr_output_head_v1#4278190119)
[3956087.893] {Default Queue}  -> zwlr_output_configuration_head_v1#5.set_position(0, 1080)
applying profile output 'DP-1' on connected head 'DP-1'
[3956087.897] {Default Queue}  -> zwlr_output_configuration_v1#3.enable_head(new id zwlr_output_configuration_head_v1#6, zwlr_output_head_v1#4278190080)
[3956087.904] {Default Queue}  -> zwlr_output_configuration_head_v1#6.set_position(0, 0)
[3956087.907] {Default Queue}  -> zwlr_output_configuration_v1#3.apply()
[3956133.659] {Display Queue} wl_display#1.delete_id(6)
[3956133.680] {Display Queue} wl_display#1.delete_id(5)
[3956133.684] {Default Queue} wl_registry#2.global(49, "wl_output", 4)
[3956133.687] {Default Queue} wl_registry#2.global(50, "wl_output", 4)
[3956133.690] {Default Queue} zwlr_output_head_v1#4278190080.position(1920, 1080)
[3956133.693] {Default Queue} zwlr_output_head_v1#4278190119.position(0, 1080)
[3956133.696] {Default Queue} zwlr_output_manager_v1#4.done(3)
[3956133.702] {Default Queue} zwlr_output_configuration_v1#3.succeeded()
[3956133.715] {Default Queue}  -> zwlr_output_configuration_v1#3.destroy()
configuration for profile 'my-home' applied
```

</details>

With `autoEnableOutputs=no`, the output DP-1 is placed above the output eDP-1. But with `autoEnableOutpus=yes`, the output DP-1 is placed at the left of the output eDP-1.

**Comment by jlindgren90** [comment]
> LGTM
> 
> Optionally consider the following:
> 
>     1. Embellish the commit message of `output: handle outputs that are enabled but not yet added` to give some context.

Sure, can do

>     2. Add a note in the man page regarding how kanshi can be used with core.autoEnableOutputs=false. Maybe include an example kanshi config.

I'd probably link to the kanshi manpage or website instead, no need to duplicate information.

>     3. Adding a couple of sentences to the troubleshooting page on the homepage to help people find this option. I can't quite remember the use-case / context, but remember we've had several people reach out about it.

Sure, can do

**Comment by jlindgren90** [comment]
I expanded the 2nd commit message with more background. I ran out of time for now to add more troubleshooting documentation.

**Comment by johanmalm** [comment]
> I expanded the 2nd commit message with more background. I ran out of time for now to add more troubleshooting documentation.

Thanks. Let's go for it :smile:

**Comment by johanmalm** [comment]
@jlindgren90 

I've just restarted and get weird output resolution now.

I have not added `core.autoEnableOutputs` to `rc.xml`

I have tried with/without kanshi running, but it makes no difference. I only have position stuff in there anyway.

Expected behaviour: My `HDMI-A-1` screen should start in 1920x1080

Actual behaviour: It starts in 1280x720


<details>
<summary>wlr-randr</summary>

```
eDP-1 "Chimei Innolux Corporation 0x15DB (eDP-1)"
  Physical size: 340x190 mm
  Enabled: yes
  Modes:
    1366x768 px, 48.006001 Hz
    1366x768 px, 60.002998 Hz (preferred, current)
  Position: 0,0
  Transform: normal
  Scale: 1.000000
HDMI-A-1 "HP Inc. HP E233 CNC83901J4 (HDMI-A-1)"
  Physical size: 510x290 mm
  Enabled: yes
  Modes:
    720x400 px, 70.082001 Hz
    640x480 px, 59.939999 Hz
    640x480 px, 59.939999 Hz
    640x480 px, 60.000000 Hz
    720x480 px, 59.939999 Hz
    720x480 px, 59.939999 Hz
    720x480 px, 59.939999 Hz
    720x480 px, 60.000000 Hz
    720x480 px, 60.000000 Hz
    720x576 px, 50.000000 Hz
    720x576 px, 50.000000 Hz
    800x600 px, 60.317001 Hz
    1024x768 px, 60.004002 Hz
    1280x720 px, 50.000000 Hz
    1280x720 px, 59.939999 Hz
    1280x720 px, 60.000000 Hz
    1280x720 px, 60.000000 Hz (current)
    1280x800 px, 59.910000 Hz
    1440x900 px, 59.901001 Hz
    1280x1024 px, 60.020000 Hz
    1600x900 px, 60.000000 Hz
    1680x1050 px, 59.882999 Hz
    1920x1080 px, 50.000000 Hz
    1920x1080 px, 59.939999 Hz
    1920x1080 px, 60.000000 Hz
    1920x1080 px, 60.000000 Hz (preferred)
  Position: 1366,0
  Transform: normal
  Scale: 1.000000
```

</details>

**Comment by jlindgren90** [comment]
Hmm, can you bisect which commit broke it?

**Comment by johanmalm** [comment]
> Hmm, can you bisect which commit broke it?

Breaking commit: https://github.com/labwc/labwc/commit/03be489eb973279585e0ca4ddde9820e1017ca86

Get this log:

```
00:01:22.292 [ERROR] [backend/drm/atomic.c:79] connector HDMI-A-1: Atomic commit failed: Device or resource busy
00:01:23.025 [ERROR] [backend/drm/atomic.c:79] connector HDMI-A-1: Atomic commit failed: Device or resource busy
00:01:27.591 [ERROR] [backend/drm/atomic.c:79] connector HDMI-A-1: Atomic commit failed: Device or resource busy
```

**Comment by jlindgren90** [comment]
Nothing is standing out to me as a possible explanation. 

Do you use rc.reuse_output_mode or adaptive sync? 

Can you add wlr_log statements to trace which return path output_test_auto takes?

**Comment by johanmalm** [comment]
No `reuseOutputMode` or adaptive sync.

Get the same with no config file.

Not using kanshi whilst testing this.

Exit through line 305

https://github.com/labwc/labwc/blob/ae8012a5804bc4787030f22da28c9c5f99f921c8/src/output.c#L305

Sorry for rushed response. Can dedicate some more time this evening.

**Comment by jlindgren90** [comment]
@johanmalm can you try https://github.com/jlindgren90/labwc/commit/384bd9252ee95740bab0049082e1d1ce9045bec0 ?

Also - happy new year!

**Comment by johanmalm** [comment]
HNY to you :smile:

Yes with your auto-enable-outputs branch commit 384bd925 everything works as expected. That logging on the commit before is very nice too!

**Comment by jlindgren90** [comment]
Great, I'll create a new PR

**Pull request merged**
